### ISSUE TITLE
Updates to Forum Recommended Services - Square

### ISSUE THREAD

**Issue by simon1066** [zencart/documentation#1016]
As requested, I'll document some changes needed to the Forum's Recommended Services section. Namely to change the references of the Square Payments plugin to the new WebPay module by directing the reference links to the Docs section on Square WebPay instead of https://www.zen-cart.com/content.php?349-Square-Payments-for-Zen-Cart

Square Payments is referenced on two Recommended Services pages

https://www.zen-cart.com/content.php?3-recommended-services
https://www.zen-cart.com/content.php?14-Payment-Processing

Rather than them link to https://www.zen-cart.com/content.php?349-Square-Payments-for-Zen-Cart they should link to the Docs,
https://docs.zen-cart.com/user/payment/square/

There is at least one bit of info in https://www.zen-cart.com/content.php?349-Square-Payments-for-Zen-Cart that would be useful to have in the Docs. I am happy to go through that page, extract any relevant info and add it to the Docs. I'm moving between PC's at the moment so will need time to remember how to install Hugo/Docsy/SourceTree, again.

**Comment by scottcwilson** [comment]
Thanks for doing this.  @zcwilt LMK if you can fix or shoot me a note with some guidance.
