### ISSUE TITLE
Loading an init_script

### ISSUE THREAD

**Issue by simon1066** [zencart/documentation#1025]
Following the instructions on how to load an init_script, https://docs.zen-cart.com/dev/code/init_system/#init-scripts, I used this code in an autoloader file:

```
$autoLoadConfig[201][] = array(array('autoType'=>'init_script',
                             'loadFile'=> 'init_addit_image_bg.php'));
```
In ZC v1.5.8a & PHP 8.0.17 I get PHP Warnings (can post the complete log)

```
PHP Warning:  Undefined variable $_SESSION
PHP Warning:  Trying to access array offset on value of type null in
PHP Warning: Undefined array key "autoType" in
```
Whereas using, from examples in ZC core code, this code produces no warnings:

```
$autoLoadConfig[201][] = array('autoType'=>'init_script',
                              'loadFile'=> 'init_addit_image_bg.php');
```

Not sure if the instructions are incorrect or that I'm misinterpreting them.

**Comment by scottcwilson** [comment]
It looks as though you have found a bug in the docs.  Would you please submit a PR ?

**Comment by simon1066** [comment]
Sure, will do. New PC is up and running so should be able to do so soon.

**Comment by scottcwilson** [comment]
Thanks for double checking this and helping get the docs right!
