### ISSUE TITLE
Search-result links to /old/ docs broken

### ISSUE THREAD

**Issue by torvista** [zencart/documentation#1106]
Search "Tools", Link From result "Development Tools" broken:

![2023-08-25 15_48_01-zencart _--_ tienda - Folder Compare - Beyond Compare](https://github.com/zencart/documentation/assets/4391026/5221d590-d287-400e-b767-8700f7262a55)

**Comment by scottcwilson** [comment]
Yeah, I have tried to exclude /old/ from indexing without much success.

**Comment by scottcwilson** [comment]
@torvista Would you please recheck?  This may be fixed now.
