### ISSUE TITLE
Wholesale Functionality

### ISSUE THREAD

**Issue by torvista** [zencart/documentation#1118]
Some placeholders/barebones headings required.

**Comment by scottcwilson** [comment]
Please PR.

**Comment by torvista** [comment]
I may flesh out documentation in the places where it is mentioned but I'm not going to guess where to create those places.

**Comment by scottcwilson** [comment]
If you have some content in markdown please attach it here.

**Comment by torvista** [comment]
I've not had time to code all the minor improvements necessary (for my/my trade customers use), and to consequently suggest them, so I think this aspect of ZC is still in its infancy. But since it's the only functionality addition for the next release, perhaps others should be polishing it as a matter of urgency.

Little documentation is really needed, the only things to know so far are:
Once a customer has a Wholesale level assigned, when logged in, other discounts are not applied (Specials, Salemaker).
For a simple product: set wholesale discount levels in base product edit as expected.
For a product with attributes: wholesale discounts must also be applied to individual attributes or instead of the base product discount.

**Comment by scottcwilson** [comment]
https://github.com/zencart/documentation/pull/1131
