### ISSUE TITLE
Upgrade Algolia DocSearch

### ISSUE THREAD

**Issue by simon1066** [zencart/documentation#1119]
The Docs currently use version 2 of DocSearch and I believe it would benefit from a upgrade to version 3.

https://docsearch.algolia.com/docs/docsearch-v3/ - top right on that page is a working v3 search box. Investigations show that changes are needed to the following files:

`\layouts\partials\hooks\body-end.html`
`\layouts\partials\hooks\head-end.html`
`\layouts\partials\search-input.html`

there may be more depending on what fine-tuning is required.

I have not been able to fully test it on ZC Docs as the new configuration requires the `appId`, which I do not have.

https://docsearch.algolia.com/docs/migrating-from-v2/

I would be happy to progress this further if need be.

**Comment by scottcwilson** [comment]
@drbyte Can you provide this information?

**Comment by drbyte** [comment]
I'll dig them up. 
But in the meantime, does it work to use the Testing credentials Algolia offers? https://docsearch.algolia.com/docs/docsearch-v3/#testing

**Comment by simon1066** [comment]
Yes, I have used the test credentials but that causes the search results to reference https://docsearch.algolia.com

![4](https://github.com/zencart/documentation/assets/13421449/e73fc0c9-a0ab-4ff2-82ca-08e766a28537)

**Comment by drbyte** [comment]
Here is the new v3 app Id: `7KE9ZZBAHM`

**Comment by drbyte** [comment]
Does our implementation also need an api Key for the frontend?

**Comment by simon1066** [comment]
I was using the same apiKey (and indexName) as in `\layouts\partials\hooks\body-end.html` but this generates no search results and a console error of

`Invalid Application-ID or API key`

so it's possible that we'll need a different apiKey.

**Comment by drbyte** [comment]
Yes, looks like we'll need this key to go with the appID: `760301bb4e25c5033d9bdc12ae15598c`

**Comment by simon1066** [comment]
Thank you, that did it. I'll see if anything needs tweaking and submit a PR.
