### ISSUE TITLE
Search autocomplete displays HTML entity

### ISSUE THREAD

**Issue by simon1066** [zencart/documentation#1124]
A side effect of the recent upgrade to Algolia v3 seems to be that the `>` character in the title of some pages is being replaced with `&gt;` in the search autocomplete popup.

Many instances of `>` are rendered correctly but it appears that the issue occurs when this character is present in the frontmatter (title) of a page. It may just be a coincidence that these pages are also those which are being generated by the build process i.e. those in `\content\user\admin_pages\configuration`. 

E.g. type `configuration minimum values` into the search box to see the issue.

I have not been able to find a solution to this. The closest I have come is to consider https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/in-depth/data-sanitization/

<img width="557" alt="Screen Shot 2024-01-10 at 2 59 48 PM" src="https://github.com/zencart/documentation/assets/404472/a3665506-6b6f-4e9a-8a0b-06886c9b55d7">

**Comment by simon1066** [comment]
If it's correct that these titles are being generated by the build process then it might be possible to use the corresponding Unicode character for `>`, instead. I'm unsure because I'm not familiar with the auto-generation process of those pages.

https://discourse.algolia.com/t/algolia-autocompletes-html-templates-how-to-use-html-entities-such-as-bull/17303

**Comment by simon1066** [comment]
For those who are interested, other than @scottcwilson, the build process for admin pages carried out by a script of Scott's. Therein lies the generation of `>` so this would obviously be the place to experiment with using a replacement value such as unicode.

Difficult to experiment on my local copy, with changes to that `build_doc.php` script, as the search automplete uses Algolia's index of crawled pages.

**Comment by scottcwilson** [comment]
Thanks for writing this up Simon.

**Comment by drbyte** [comment]
I'm uncertain what delays may exist in seeing changes, so I've done a few changes to characters to see whether `&gt;` alters to something else as confirmation.

**Comment by scottcwilson** [comment]
Tests we can run once Chris' PR is ready by Algolia: 

```
Configuration Credit Cards
Configuration Customer Details
Configuration Define Page Status
Configuration Email
```

Hopefully one of these will be the required magic.

**Comment by drbyte** [comment]
`≫` looks the most promising:

<img width="167" alt="Screen Shot 2024-01-10 at 3 22 55 PM" src="https://github.com/zencart/documentation/assets/404472/752e634b-0bd4-4d8b-b8ba-155a79ccd5af">

**Comment by drbyte** [comment]
Scott, do you wanna update your build script to use `≫`, and push that.

Then whenever Algolia updates their "headings" in search results, it should all sync up.

**Comment by drbyte** [comment]
Just the literal character symbol, not marked up with anything.

**Comment by drbyte** [comment]
Okay, reindexing is completed:
<img width="558" alt="Screen Shot 2024-01-10 at 5 29 34 PM" src="https://github.com/zencart/documentation/assets/404472/d0a3198f-bb7e-4e74-ad4c-bba4096c8ce6">

And reindexing now occurs daily at 3am UTC

**Comment by scottcwilson** [comment]
Done.  @simon1066 Please close when confirmed.  

Thanks for getting the indexing sorted @drbyte.

**Comment by scottcwilson** [comment]
I wonder why this problem doesn't occur for `user/admin_pages/customers/orders_invoice.md`. Search for "Orders Invoice" and you'll see the `>` is rendered without transformation.  (Not suggesting a change, just curious why it works this way.) 

I'm documenting the change to `≫` as required for content in `/user/admin_pages/configuration`.

**Comment by simon1066** [comment]
When I search for "Orders Invoice" & "Orders Packing Slip" I do see the transformed character (`&gt;`). Perhaps you were noticing the instance under "Customers"?

![Screenshot 2024-01-12 141448](https://github.com/zencart/documentation/assets/13421449/2b2336e3-5672-4d83-b236-51f81387d089)

**Comment by scottcwilson** [comment]
Let me reopen because there's apparently still work to do.  My mistake was not focusing on titles - the body text is correct just not the titles.  I will knock this out in the next few days.   Thanks @simon1066 for pointing me in the right direction.

**Comment by scottcwilson** [comment]
I'll do some retesting tomorrow AM after the reindex.

**Comment by drbyte** [comment]
Manual reindexing completed.

**Comment by simon1066** [comment]
That's all good now. All previous instances of `>` in the frontmatter title now display as `>>` in instant search.

**Comment by scottcwilson** [comment]
> Manual reindexing completed.

Chris, would you please send e the commands for this so I can add them to our build docs.
