### ISSUE TITLE
info on .htaccess redirect/rewrites for moved products

### ISSUE THREAD

**Issue by torvista** [zencart/documentation#1180]
For a deleted/obsolete product, if the correct procedure is a .htaccess rule to 302 redirect to the new product or elsewhere, I've a couple of pointers to add that cost me a lot of time to discover.
I don't see a relevant page where I can add this info.

**Comment by scottcwilson** [comment]
Thank you - I will get you a page in the next 48 hours.  These are very useful insights.

**Comment by scottcwilson** [comment]
https://docs.zen-cart.com/user/seo/deleted_product_redirects/
please proceed.

**Comment by scottcwilson** [comment]
Closed by #1191
