### ISSUE TITLE
Link to support site/forum

### ISSUE THREAD

**Issue by simon1066** [zencart/documentation#1187]
Small thing. I know everyone's busy with v2.0, but while I'm tinkering on my local copy with the layout and structure of the docs (I'll post a link to it if I come up with anything of use) I thought that the homepage would like to have a link back to the support site forum. I've just added an icon to the right of the footer. It requires a change to `config.toml` and I'll PR if you're ok with that.

![Screenshot 2024-02-28 140036](https://github.com/zencart/documentation/assets/13421449/98fc14de-d9d2-4783-8956-3ea43bc53749)

**Comment by scottcwilson** [comment]
Sure, thank you.
