### ISSUE TITLE
Adding Sanitisation to existing page

### ISSUE THREAD

**Issue by brittainmark** [zencart/documentation#142]
I would like to know how i would add sanitisation for a field that I add to say product details. So i add a field called product location which i want to be SIMPLE_ALPHANUM_PLUS.
should I create a file in /admin/includes/extra_datafiles/ say called product_details.php
and include the code.
$sanitizer = AdminRequestSanitizer::getInstance();
$group = array(
    'id' => array('sanitizerType' => 'SIMPLE_ALPHANUM_PLUS', 'method' => 'both', 'pages' => array('products_details'), 'params' => array()),
    );
$sanitizer->addComplexSanitization($group);

is it really that simple?
I assume that I would also have to include some validation in the  updateproduct module etc. or is it ok to just assume that the sanitiser has done the job?

I have also added fields into shipping/and packing gID=7 at the moment they contain html and are altered to &lt; etc so i update via database. but was wondering if this routine could be used in the future versions of zen cart to do the sanitisation?

**Comment by scottcwilson** [comment]
Hi there!  Great question, but could I get you to post this on the forum or the code issues page?  This site is just for documentation.
