### ISSUE TITLE
Build Markdown file from Notifiers report

### ISSUE THREAD

**Issue by scottcwilson** [zencart/documentation#169]
I'd like to run the Notifiers Report 

https://github.com/lat9/notifier_report 

at release time and post the file to the docs area, but I'd need the file to be markdown - can you output a markdown file for use by the docs?  Doesn't have to be fancy.

**Comment by lat9** [comment]
Do you have a preferred markdown layout that I could use?  Otherwise, this feels like it's going to be a [fetch a rock](https://www.urbandictionary.com/define.php?term=rock%20fetch) exercise. 

Ditto for the 'formatted file', preferred layout, please.

**Comment by scottcwilson** [comment]
If you look at the current contents of https://docs.zen-cart.com/dev/code/notifier_report/ you'll see a layout that would work.  

The wording of my request was confusing - I only need a markdown output.  That was the formatted file.

**Comment by lat9** [comment]
I did not see that base layout; that helps!

**Comment by scottcwilson** [comment]
Thanks for doing this - it will be a big improvement to the documentation over the simple list I have now.

**Comment by lat9** [comment]
I've updated the [Notifier Report](https://github.com/lat9/notifier_report) to produce a markdown-formatted output.  Let me know if that meets your expectations.

**Comment by scottcwilson** [comment]
Beautiful! Thank you so much for doing this.   
It's now live.

PS> You can remove the front matter if you want - my intention was that it would just stay in the file `code/notifiers_list.md` because I had to do extra writeup there anyhow.
