### ISSUE TITLE
What are the Server Requirements for running Zen Cart?

### ISSUE THREAD

**Issue by dbltoe** [zencart/documentation#177]
Don't have time to work it just yet, but I was thinking this should be worded so we don't have to come back every 30 days to edit the file due to a PHP or MySQL change.

We are currently recommending PHP 7.0 with an EOL of over a year ago.

A healthy balance between providing information and providing a link to current information is always best IMHO

**Comment by scottcwilson** [comment]
Where are you seeing we recommend PHP 7.0? 
https://docs.zen-cart.com/user/first_steps/server_requirements/

**Comment by dbltoe** [comment]
https://docs.zen-cart.com/user/first_steps/server_requirements/#php-version in red NOTE under versions

**Comment by scottcwilson** [comment]
This says PHP 7, not PHP 7.0.  We are not recommending PHP 7.0.   But I can change it to "a supported PHP Release" or something more generic.

**Comment by scottcwilson** [comment]
"You should be moving to a currently supported version of PHP 7+ as soon as possible"
Does that work for you?

**Comment by dbltoe** [comment]
I was thinking we could let the PHP link provide the info and make it where we wouldn't have to check if we were current.  Perhaps combine the What About Old PHP... and the NOTE into one red paragraph sending folks to PHP.  I think accuracy would outweigh the possible annoyance at clicking just once more.  Personally, I seldom stop at one source and don't mind clicking away.
It's not an OMG to me.  Just the old "put a link or add it to the DB so we don't have to find it later to change" kind of guy.

**Comment by scottcwilson** [comment]
Would you please write up wording that you think would be clearer?  Just put it here and I'll update the document.

**Comment by drbyte** [comment]
I've made a number of updates to the page

https://docs.zen-cart.com/user/first_steps/server_requirements/

I intentionally left mentions of PHP 5.6 and "early versions of PHP 7" being obsolete, since those are also listed in the "ZC supported PHP versions" grid above it, and I want people to have a visual reminder there that even those are listed, they're not supported. I realize that when PHP 8 comes out things will change again. PHP publishes a new major-ish version annually now, so changing it once a year isn't all that bad in terms of maintenance effort, especially since we need to add more notes about newer ZC versions from time to time too.

What are your thoughts on the new wording?

**Comment by scottcwilson** [comment]
Good stuff.  One small tweak: Please update the "last updated" date at the top - or if you want I could add some Hugo logic to show the last updated date.

**Comment by scottcwilson** [comment]
To me, the red text was really aimed at 5.6 people running old carts, so it wasn't bad, but this is better.

**Comment by dbltoe** [comment]
Will do sometime soon.

**Comment by drbyte** [comment]
> Good stuff. One small tweak: Please update the "last updated" date at the top - or if you want I could add some Hugo logic to show the last updated date.

I left that because that's the last time the actual Zen Cart "requirements" were updated.

**Comment by scottcwilson** [comment]
That's a distinction that will not be meaningful to most people.  I'm suggesting updating it because now, PHP 7.1 is obsolete; that wasn't true in Dec 2019.   

Anyhow it looks better now, thanks for doing that.   @dbltoe are we clear to close this issue?

**Comment by dbltoe** [comment]
Looks good to me.
