### ISSUE TITLE
How do I Install Zen Cart?

### ISSUE THREAD

**Issue by dbltoe** [zencart/documentation#179]
Not an issue, just a thought for all to ponder in Item B, Upload the Zen Cart fileset to your webserver.

With the continuing problem of FTP failures from slow or intermittent connections, what we tell folks (especially for upgrading) is to FTP the fileset zip.  Then, use your cPanel file manager to unzip the file, change the folder name from zen-cart-v1.5.6c-#### to test, store, tryout, whatever....

Regardless whether installing or upgrading, the danger of bad FTP is gone.  It's certainly faster to work on the server than over FTP. Initial site setup can be done without prying eyes.  And, when ready for prime time, either a 301 or a move to the root.

To me, the move to the root is "safer" than extracting the files and then uploading.

To date, we've not experienced problems with this method and we have a few out there that are "challenged".

I can see both sides, but I'm kinda 70/30 toward the zip upload.

Thoughts?

**Comment by dbltoe** [comment]
Sorry, just read a little further.  Are any of you still doing C.?  Can't remember when last we didn't just let the installer do its thing.
What about the servers that don't like 777?  Do we mention 755 and 644 elsewhere?
Sorry, not trying to rock the boat.  Just trying to read like a noob.

**Comment by drbyte** [comment]
A clear step-by-step addition for the zip file approach is welcome.

Those without cPanel won't be able to do that though. So they need to know how to upload the files directly.

As to 777 permissions, most servers don't like that. But if we tell people to set the values too restrictively then they'll be locked out and something needs to be said about how to fix that. Sigh. Permissions are always such a nuisance when you can't expect what a given host actually implements. Granted, it's way better nowadays (most of those 777 docs were from the mid-2000's when hosting had PHP owning files at different permissions then the FTP user could access, meaning everything required a lot of hand-holding). We can safely modernize much of this section.

**Comment by scottcwilson** [comment]
John, please submit your changes as PRs.  Yes, I always use the zip method for transfers of large numbers of files.

**Comment by scottcwilson** [comment]
Closing subsequent to merge of #195
