### ISSUE TITLE
Configuration Settings help vs auto-generated script

### ISSUE THREAD

**Issue by drbyte** [zencart/documentation#191]
You keep saying doc info is generated automatically by a script. Will the script need to be run  again if changes occur? Does the script create the pages? If we edit the docs.zencart, does that make a permanent change that will not be overwritten by running the script again? I can definitely get started adding info into the docs. I just need clarity here. 
I'm just trying to figure out what's going on.

_Originally posted by @wiztechinc in https://github.com/zencart/zencart/issues/3293#issuecomment-615925585_

**Comment by scottcwilson** [comment]
> You keep saying doc info is generated automatically by a script. 

Some of the pages are automatically generated.  If you start reading in the CONTRIBUTING document, it shows you how to figure this out. 

> Will the script need to be run again if changes occur? 

If there is a database change, you would want to run the script again.  This would be once per release typically. 

> Does the script create the pages? If we edit the docs.zencart, does that make a permanent change that will not be overwritten by running the script again? 

The pages that are auto generated are ones that are based on database content.  Other pages are not autogenerated and can be freely edited.  

See https://github.com/zencart/documentation/blob/master/CONTRIBUTING.md#developer-docs

**Comment by drbyte** [comment]
So what's your recommendation if community members want to provide extra context or add suggestions around "best practices" when using these configuration settings?

**Comment by scottcwilson** [comment]
Already handled.  Go to `user/admin_pages/configuration/` and view the file `developers_read_me.txt`. 

Here's what it says: 
---
Please do not hand edit these files; they are created automatically from a 
fresh install of the latest release. 

If you find a typo: 
- Report it on the forum.  The page will be corrected, and the 
typo will be fixed in the schema creation script and the next version's
update script. 

If you want to add content to a page:
- Report it on the forum.  The build process will be updated to add it. 
You can see an example where this has been done at 

https://docs.zen-cart.com/user/admin_pages/configuration/configuration_emailoptions/#email_archiving_active

In the unlikely event that a new configuration menu is added, please update 
content/user/admin_pages/configuration/all.md

The code that created these `.md` files is the `build_doc.php` script, which is stored at https://github.com/scottcwilson/zencart_tools.

---

**Comment by scottcwilson** [comment]
The existence and importance of the `developers_read_me.txt` for the content which is automatically created (`/user/admin_pages/configuration/` and `/dev/schema/`) is noted in the `CONTRIBUTING.md` file.

**Comment by scottcwilson** [comment]
> So what's your recommendation if community members want to provide extra context or add suggestions around "best practices" when using these configuration settings?

... but truly, rather than modify `admin_pages/configuration`, it would probably be better to add to the `/admin` folder, where longer form content can easily be added.   Generally the content in `admin_pages/configuration` doesn't link out to the rest of the docs site.

**Comment by torvista** [comment]
Hmmm. To be brutal, what is the point of listing the configuration constants?

I would say for 

a) a web search on the constant, to find the constant with an expanded description. Not sure who would need that. If you have the constant name, you search in the code.

b) a web search on the option title, for a more detailed description of the configuration option. But a detailed description of the option should be built-into the admin already (as discussed elsewhere).

The only use I see for this listing is as a staging ground/an easier way for user-people to add comments that dev-people can incorporate into the next release. If an option in the cart needs further explanation than is already in the description, that description is inadeqate.

**Comment by torvista** [comment]
Hmmm. To be brutal, what is the point of listing the configuration constants?

I would say for

a) a web search on the constant, to find the constant with a description. Not sure who would need that. If you have the constant name, you search in the code/Developers Toolkit.

b) a web search on the option title, for a more detailed description of the configuration option. But a detailed description of the option should be built-into the admin already (as discussed elsewhere). If an option in the cart needs further explanation than is already in the description, that description is inadequate/needs to be improved.

c) a web search on the description/function, to meet a need. Possibly of use to get new users.

The only use I see for this listing is as a staging ground/an easier way for user-people to add comments/suggestions that dev-people can incorporate into the next release. It should not be better information than that built-in, or only until the next release when the cart is updated with the comments, the comments get cleared, and the new content from the cart replaces what is here. It should all be about improving the cart..."don't make me <s>think</s> search".

**Comment by scottcwilson** [comment]
> Hmmm. To be brutal, what is the point of listing the configuration constants?

To tell people how to customize their system through the admin.  Many storeowners don't think of themselves as developers and wouldn't be drawn to the developer's toolkit. 

You don't have to use this page if it's not useful for you.  But for some users, this it will be useful to be able to see this information.

**Comment by scottcwilson** [comment]
Here's a specific use case: the storeowner thinks, I wonder if I can display some products on the shopping cart page when there are no products in the cart?  

He goes to 
https://docs.zen-cart.com/user/admin_pages/configuration/all/

Search for "shopping cart".  Second hit shows 
"Show New Products on empty Shopping Cart Page" and friends.
Path indicates: "Path: Configuration > Stock"

So now he knows to go to the Configuration > Stock page to tweak these settings.

**Comment by scottcwilson** [comment]
Can this ticket be closed?
