### ISSUE TITLE
URL makes no sense

### ISSUE THREAD

**Issue by barco57** [zencart/documentation#199]
URL: https://docs.zen-cart.com/user/new_user_topics/change_powered_by/
Page title: How do I change the logo or the logo alt text in the header?
breadcrumb: Storeowner Docs / New User Topics / How do I change the logo or the logo alt text in the header?

**Comment by scottcwilson** [comment]
I agree but most folks don't spend a lot of time reading URLs.

**Comment by drbyte** [comment]
Probably good to make it consistent.

Especially when "change powered-by" is a different popular question

**Comment by scottcwilson** [comment]
Fixed.
