### ISSUE TITLE
Feedback widget use of JS arrow function

### ISSUE THREAD

**Issue by mc12345678** [zencart/documentation#202]
Initiated a post in the forum: https://www.zen-cart.com/showthread.php?226626-Display-and-operation-issues-with-docs-zen-cart-com

Where I identified that there was an issue accessing the docs.zen-cart.com site.  One of the issues identified was a javascript issue that I believe I have tracked down, the question is how to obtain resolution (if it is to be resolved).  It appears that the feedback.html partial file (apparently from docsy) uses a short form of javascript function assignment to a variable:
````javascript
const disableButtons = () => {
````
and
````javascript
const sendFeedback = (value) => {
````
While I can not comment on this being "appropriate" use or not, but in independent testing from my device, I have been able to confirm that if those lines had been written as:
````javascript
const disableButtons = function() => {
````
and
````javascript
const sendFeedback = function(value) => {
````
then they would execute successfully or at least not error at those line(s)...

I have found through other review that at least one file/location where this is contained in docsy is at: 
https://github.com/google/docsy/commit/65c93dad0664f3413c2375dbb4ce81e9fea1d40e

Where the feedback element was first incorporated.

I am making a note at that site/location about this issue as I suspect (since not finding the partial file feedback.html on this site) that the package is used/drawn from to provide the docs site.  Therefore it seems that for it to be corrected it has to go through a third party and not through the ZC community.

**Comment by drbyte** [comment]
For your Blackberry Classic mobile device where this is occurring, what javascript engine (and version) does it use?

According to W3C and [Mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Browser_compatibility) arrow functions started being supported in May 2013 by Firefox, and all other modern browsers support them. (I argue that IE is no longer a modern browser.)

**Comment by drbyte** [comment]
Maybe we don't need the feedback widget at all, since its end result is to point to the docs repo for "actual" feedback. (I gather it increments a counter somewhere too.) We already have links to repo suggestions, so perhaps the widget serves no useful purpose. IMO it just clutters the screen.

**Comment by mc12345678** [comment]
Additional information, having looked into the use of arrow functions: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

A similar javascript error occurs on IE.  Tested and validated on IE11 with javascript stopping at the same line; however, the footer appears in the correct location and the feedback "tool" appears..

Ok, so just finished reading DrB's comment about IE... 

It's taking me longer than expected to find that version information (never really searched for it before), but I am able to say that the overall OS is of the 10.3.3 flavor. I'll continue searching, but wanted to respond sooner rather than later.

**Comment by drbyte** [comment]
I updated the feedback.html by overriding the original template, and rewrote those 2 functions to no longer be ES6 arrow functions. So the JS error should be gone now.

**Comment by mc12345678** [comment]
Yeah, as expected it had an issue with the similar assignment in code below that:
````javascript
yesButton.addEventListener('click', () => {
````
I assume:
````javascript
yesButton.addEventListener('click', function() => {
````
would resolve that one (and the following for noButton) as well.

**Comment by mc12345678** [comment]
BTW (and can open a separate issue), here are the images that I am seeing as a result of whatever is causing the formatting issue(s).

![IMG_20200422_120959](https://user-images.githubusercontent.com/2072812/80008442-c64ab600-8495-11ea-9e18-abf8ba0bd8fd.png)
![IMG_20200422_121016](https://user-images.githubusercontent.com/2072812/80008445-c6e34c80-8495-11ea-9860-ca89a6f68a4f.png)
![IMG_20200422_121023](https://user-images.githubusercontent.com/2072812/80008446-c6e34c80-8495-11ea-95c9-6a056a46c1f4.png)

**Comment by drbyte** [comment]
I'd be very interested in knowing what limitations that browser has vs other modern browsers, in order to understand how far back we need to downgrade the technology in order to support it.

**Comment by scottcwilson** [comment]
@mc12345678 would you please TRIPLE CHECK to be sure your cache is cleared?  This EXACT issue happened early on in the movement of the docs - I had to cull out all the old formatting and it took a few tries.

**Comment by drbyte** [comment]
> Yeah, as expected it had an issue with the similar assignment in code below that:

I've updated the other 2 functions similarly.

**Comment by scottcwilson** [comment]
> Maybe we don't need the feedback widget at all, since its end result is to point to the docs repo for "actual" feedback (after sending the "click" event to Google Analytics). We already have links to repo suggestions, so perhaps the widget serves no useful purpose. IMO it just clutters the screen.

This page has no feedback; how does it look? 

https://docs.zen-cart.com/user/about_us/in_memoriam/

**Comment by mc12345678** [comment]
Console for my browser and for IE both have the below similar messages
````javascript
Viewport argument key "shrink-to-fit" not recognized and ignored. 
jQuery.Deferred exception: undefined is not a function (evaluating 'headings.forEach') https://docs.zen-cart.com/js/main.min.e67709780baf9b96e718d9cd19859799e70b8d106c0200b245581e72e78142df.js:5:80
l@https://code.jquery.com/jquery-3.3.1.min.js:2:29379
https://code.jquery.com/jquery-3.3.1.min.js:2:29677 undefined jquery-3.3.1.min.js:2
TypeError: undefined is not a function (evaluating 'headings.forEach') main.min.e67709780baf9b96e718d9cd19859799e70b8d106c0200b245581e72e78142df.js:5
````
I've had this issue since the SSL was resolved and I don't recall being able to access it before then. 

The difference between the two browsers is that IE shows the left side sidebox with the footer at the bottom while my browser doesn't display the left sidebox to the "side" the html results in a small stripe of space just below the upper blue border with no content in that "sidebox". Yes deleted cache and cookies via my browser debug tool. Issue still exists on that unfortunate page making it to where I pretty much can't see the important part of the page...  I can attach the html and possibly the css if it would be of any benefit...  Take me a moment to capture it all, but if it would help.

Also still trying to figure out how to determine the requested JS info...  

Other quick update, able to get through the feedback JS portion.

**Comment by drbyte** [comment]
Again, which browser is this? IE and what?

**Comment by mc12345678** [comment]
Sorry, trying to look at the issues from as many directions as possible.  My browser is the default browser provided with Blackberry Classic using OS 10.3.3. In testing I wanted to see what the console shows using various browsers as it seems each is able to identify something different than another browser seems to just ignore. The other browser used and described above was IE11.

So console messages from IE11 are:
````javascript
- Tag cannot be self-closing. Use an explicit closing tag. in_memoriam (80,183)
- Character reference is missing an ending semicolon ";". in_memoriam (111,79)
- jQuery.Deferred exception: Object doesn't support property or method 'forEach' TypeError: Object doesn't support property or method 'forEach'
   at Anonymous function (https://docs.zen-cart.com/js/main.min.e67709780baf9b96e718d9cd19859799e70b8d106c0200b245581e72e78142df.js:5:65)
 at l (https://code.jquery.com/jquery-3.3.1.min.js:2:29367)
at Anonymous function (https://code.jquery.com/jquery-3.3.1.min.js:2:29677) undefined
- SCRIPT438: Object doesn't support property or method 'forEach': jquery-3.3.1.min.js (2,31040)
````

The content on the associated lines is:
````javascript
<svg id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 200 200" enable-background="new 0 0 200 200">

<input type="search" class="form-control td-search-input" placeholder="&#xf002 Search this site…" aria-label="Search this site…" autocomplete="off">


("jQuery.Deferred exception: "+t.message,t.stack,n)},w.readyException=function(t){e.setTimeout(function(){throw t}
````

With a row separating each issue's line/highlighted area.

These were all identified on the following page: https://docs.zen-cart.com/user/about_us/in_memoriam/

In Microsoft Edge Version 81.0.416.58 the following message was in the console:
````javascript
Unchecked runtime.lastError: The message port closed before a response was received.
````
Which is a completely useless message.

In Firefox Developer Edition Version 69.0b7 (64-bit), there are no messages in the console log after loading the page.

Same (issues in console) for Firefox Version 72.0.2 (64-bit).

And last tested browser was Google Chrome DevTools (Chrome 80) with nothing specific to identify from the console.

Now, I've seen my browser be picky about HTML format so ran validator: https://validator.w3.org/nu/?doc=https%3A%2F%2Fdocs.zen-cart.com%2Fuser%2Fabout_us%2Fin_memoriam%2F

There's a few "errors" reported :/ ... 

So again, not sure what has led to what as I've gone through a number of various tests/analyses...
