### ISSUE TITLE
What are the Server Requirements for running Zen Cart?

### ISSUE THREAD

**Issue by proseLA** [zencart/documentation#205]
scott,
i think this page should not be dug in as far as it is.  at a minimum, i think it should at least be on the all time favorite list.  i refer to it constantly (mostly because i can not remember anything), and it would be nice if i did not have to dig to find it all the time.

just my thoughts.

**Comment by scottcwilson** [comment]
It **is** in the all time favorites list - https://docs.zen-cart.com/user/all_time_favorites/ 

On the front page of the docs, look to the right where there's a link "Top FAQs" or on the left where there's a link "All Time Favorites."

**Comment by scottcwilson** [comment]
Also the search is astonishingly powerful - if you type in the search bar at the upper right "serv" it's the second link.

**Comment by proseLA** [comment]
i think it would be nice on the menu on the left...  i suppose eventually i will find it.  but it always seems to take longer than necessary.  no big deal..

**Comment by scottcwilson** [comment]
If you use it all the time, wouldn't bookmarking it be the way to go?

**Comment by proseLA** [comment]
no.
