### ISSUE TITLE
Template Default - what is it?

### ISSUE THREAD

**Issue by dbltoe** [zencart/documentation#208]
Is it not time to starting talking about template_default as what it really is versus a viable template to be used for a store?

IMHO, template_basefiles, master_templatefiles, or something similar would stop a lot of confusion for new users.

Since 1.5.5 and the inclusion of responsive_classic as the true "default", I see constant confusion as to which template goes where, what files need to be where, etc.

As this doc states, template_default is the master set of template files -- Don't touch.  Then, we are told that ZC comes with two other templates.  Again, confusing.

Under _**Can I use template_default?**_, it's second paragraph even implies that template_default can be reached in the Tools >> Template Selection option.  This is not an option as template_default 
does not appear a a possible choice in Template Selection.

And, "pedagogic"?!?  That will certainly drive some learning as folks drastically Google to see what this new command does in PHP or CSS.  ;-)

I can already here the cries of "This is going to screw up sooo many mods."  But, aren't we supposed to put overrides elsewhere in the first place?

**Comment by scottcwilson** [comment]
Selecting "Classic Contemporary Green" is really using Template Default.   But you're right - this could be clearer.  

I use the term "default files" here: 
https://docs.zen-cart.com/user/first_steps/overrides/

I wouldn't be that keen on introducing any more terms.

**Comment by scottcwilson** [comment]
I'm removing the phrase "the default template" since (as you point out) the real default template is now responsive_classic.  Thanks for reporting this.
