### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by dbltoe** [zencart/documentation#209]
I am currently formulating an addition to the Image Preparation - how to Page but think we need to address the line up of this page first.

IMHO, the lineup should be as close to actual operation as possible.  i.e., you wouldn't talk about adding attributes until you had covered the addition of products that might have those attributes.

What about swapping 1 & 2 to the 3 & 4 position which would make it:

Image Preparation- how to
Images -multiple image problems (and changing to **Images - Preparing for Additional Images**)
Additional Images - adding
Additional Images - disabling

**Comment by scottcwilson** [comment]
Go for it.  Thank you!

**Comment by dbltoe** [comment]
Not familiar with the process that brings in the items.  Editing that page shows nothing to rearrange.
Feeling older and more behind already.

**Comment by scottcwilson** [comment]
I'm not positive what you mean - can you explain more about the issue you're having?

**Comment by scottcwilson** [comment]
oh sorry - are you meaning you want to change the sorting of the articles on 

https://docs.zen-cart.com/user/images/

If so, just change the weight in the front matter.    See 
https://github.com/zencart/documentation/blob/master/CONTRIBUTING.md 
(search for weight)

**Comment by scottcwilson** [comment]
LOL and once you do that, please add a note to the CONTRIBUTING doc telling people how to do this.  "If you want to impose a deliberate order on the presentation of documents in a folder, set the weight for each one ... "

**Comment by dbltoe** [comment]
so... To make 1, 2, 3, 4 into 3, 4, 1, 2; it would be:
1- weight 10
2 - weight 5
3 - weight 2
4 - weight -1
?

**Comment by scottcwilson** [comment]
I like to start with 10 and do jumps of 10 because it's less brain bending.  So to get 3, 4, 1, 2 you'd have 

3 - weight 10 
4 - weight 20
1 - weight 30 
2 - weight 40 

This likely will not work in the Preview that the build system creates.  DON'T PANIC.  It will work on the final deploy.

**Comment by scottcwilson** [comment]
Brilliant!
