### ISSUE TITLE
Notifier help page improvements

### ISSUE THREAD

**Issue by scottcwilson** [zencart/documentation#219]
Would you please update

https://docs.zen-cart.com/dev/code/notifiers/

and give that article a scrub and improve the examples?  Thank you!

**Comment by lat9** [comment]
This is another _rock-fetching exercise_ as I'm unclear as to what scrub and what improvements are desired.

**Comment by scottcwilson** [comment]
LOL you and your rock fetching. 

Chris has already improved it - maybe could you fill in the heading
Listening to Multiple Notifier Hooks In A Single Observer Class 

and just go through it and see if you think anything is missing or non-obvious to the beginner.

**Comment by lat9** [comment]
I don't understand the following section:

> NB! The observer/notifier system is written for an OOP-based application, as the observer expects to attach to a class that has notifiers within its methods. However a lot of the code within Zen Cart is still procedural in nature and not contained within a class.
> 
> To work around this, we added the ‘stub’ notifier class. So if you want to create an observer for a notifier that lies within procedural code (like in page headers) you should add the notifier into your myObserver class like this:
> 
> class myObserver extends base {
>    function __construct() {
>      global $zco_notifier;
>      $zco_notifier->attach($this, array('NOTIFY_HEADER_END_CHECKOUT_CONFIRMATION'));
>    }
> 

An observer class (so long as it `extends base`) can attach to *any* notification via `$this->attach(`, whether those notifications are issued via class or procedural code.

**Comment by scottcwilson** [comment]
Agreed -but some classes don't extend base.  Above this is the sentence:

In procedural code (or outside of a class that extends base) use the global $zco_notifier object.

Do you want to reword for clarity?

**Comment by drbyte** [comment]
@lat9 is correct. I've removed the confusing paragraphs.

**Comment by lat9** [comment]
While you're there, @drbyte, the **Real World Example**'s use of:
```php
 function __construct() {
    $_SESSION['cart']->attach($this, array('NOTIFIER_CART_ADD_CART_END', 'NOTIFIER_CART_REMOVE_END'));
  }
```

... is also very funky.  Shouldn't that, also, use the `$this->attach` construct?

**Comment by drbyte** [comment]
> the **Real World Example**'s use of:
> 
> ```
>  function __construct() {
>     $_SESSION['cart']->attach($this, array('NOTIFIER_CART_ADD_CART_END', 'NOTIFIER_CART_REMOVE_END'));
>   }
> ```
> 
> ... is also very funky. Shouldn't that, also, use the `$this->attach` construct?

/me punts to @zcwilt ...

**Comment by scottcwilson** [comment]
Thanks folks, can't wait to see the updated article!

**Comment by scottcwilson** [comment]
I would dearly love to see simpler examples.

**Comment by drbyte** [comment]
> I would dearly love to see simpler examples.

meaning ?

**Comment by scottcwilson** [comment]
Modifying the cart contents is fraught with risk and complexity.  If you look at the SMS on Sale mod, it sends a one line email in an observer.  This is a small easy to understand example.   Surely there are others.

**Comment by lat9** [comment]
I'll take a crack on these updates.  @zcwilt, please wait until I'm finished so that we don't collide!

**Comment by scottcwilson** [comment]
I'm excited about this new updated page.  Cindy, please be sure to add your new tool to the "Plugins which support Notifier Use" list at the bottom of the page.

**Comment by lat9** [comment]
How about I use USU's [observer](https://github.com/lat9/usu/blob/master/includes/classes/observers/UsuObserver.php) class as an example?  It's pretty skinny and also illustrates how an observer doesn't _have to_ observe.

**Comment by lat9** [comment]
Note that I'll also be removing the reference to the Notifier Trace plugin.  That base processing has been in-core since (around?) v1.5.2.  I'll add a note about creating the `NOTIFIER_TRACE` constant to control that output.
