### ISSUE TITLE
Shouldn't code blocks 'scroll'?

### ISSUE THREAD

**Issue by lat9** [zencart/documentation#225]
Looking at https://docs.zen-cart.com/dev/code/notifiers/, there are a bunch of code blocks that overflow horizontally and, thus, wrap.

Isn't the 'standard' markdown to have a horizontal-scroll on overflow for sections delimited by '```'?

**Comment by scottcwilson** [comment]
This might help - in the front matter, add 

```
type: codepage
```

to get the full width of the page.

**Comment by lat9** [comment]
How would I go about verifying that that addition does that (other than submitting a change)?

**Comment by scottcwilson** [comment]
You should run `hugo server` locally to test your changes.  See details in README: 
https://github.com/zencart/documentation

**Comment by lat9** [comment]
There are instructions there for installation on a Mac; how does this get installed for a Windows installation?

**Comment by scottcwilson** [comment]
Maybe these links will help?  I'm not a Windows guy. 

https://gohugo.io/getting-started/installing/
https://discourse.gohugo.io/t/howto-install-hugo-on-windows/741

**Comment by lat9** [comment]
I'll just take my chances on the formatting as that just seems over-complicated.

**Comment by scottcwilson** [comment]
NP.  Remember that after you submit, it does a "test build and deploy" that you can look at, and just amend your checkin if it needs tweaking.

**Comment by scottcwilson** [comment]
This page looks good - closing this issue, but please reopen if you think that using `type: codepage` didn't do what you needed.
