### ISSUE TITLE
Document Languages

### ISSUE THREAD

**Issue by scottcwilson** [zencart/documentation#231]
Need this content
https://www.zen-cart.com/wiki/index.php/Languages

**Comment by brittainmark** [comment]
is it a straight copy? where can i get info on formatting etc.

**Comment by scottcwilson** [comment]
Some tips here: 
https://github.com/zencart/documentation/blob/master/CONTRIBUTING.md 

Start with a copy but test it to make sure it's still accurate up to 1.5.6, then if you have time document the 1.5.7 way (and test that too).  Do you know another language or can you fake it? :)

**Comment by drbyte** [comment]
Preferred to write it in the tone of whatever the latest official Zen Cart release is.

And then for anything specifically different for older versions, add those as special cases.

**Comment by scottcwilson** [comment]
Does this not adequately encourage a bias towards recency?  I'd be happy to beef it up if you think it's not sufficient. 

https://github.com/zencart/documentation/blob/master/CONTRIBUTING.md#content-recommendations

**Comment by drbyte** [comment]
I re-mentioned it here in this issue because the discussion was about making a "straight copy from the wiki", which is old-style. And your comment talked about "1.5.6 ... and then document the 1.5.7 way", which didn't sound like preferring recency.

**Comment by scottcwilson** [comment]
Oh sorry got it.  @brittainmark Use the content but start with the current state of affairs and only reference old stuff at the end if at all.  Sorry for the confusion.  

I think a lot of the content will be evergreen but we'll see.

**Comment by brittainmark** [comment]
Finally manage to get the files locally i could not get the download to work from the readme under documents. I now have a hugo error: Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): resource "scss/scss/main.scss_9fadf33d895a46083cdd64396b57ef68" not found in file cache 

any ideas?

**Comment by scottcwilson** [comment]
If you're on Windows, you might need the extended version of Hugo.

**Comment by scottcwilson** [comment]
Worst case though this is just a Markdown document so just use a Markdown editor and then submit your PR; we can tweak before the merge if need be.  Also, when you PR you get a peek of what it will look like in a "deploy preview" created by Netlify.

**Comment by brittainmark** [comment]
Yes needed the enhanced edition. Have updated the /user/admin_pages/localization/languages/ file. Have started to look at the dev docs. Its a bit more complicated than the original. I'll keep going and let you see when I have made some decent progress.

**Comment by scottcwilson** [comment]
Fantastic ! Thank you.

**Comment by brittainmark** [comment]
Thanks for the tweeks. Still learning git hub. Should I close the fork I have made and refork for further changes?
I'll look at the comments and try to take on board.

**Comment by scottcwilson** [comment]
Your fork: 
https://github.com/brittainmark/documentation 
lives on for as long as you work on the project.  

You should now update it, since the branch you created 
https://github.com/zencart/documentation/pull/295

has been merged.  Then you will create another PR and do more updates.

**Comment by scottcwilson** [comment]
(The PR is created on a new branch.  Hope this all makes sense.)

**Comment by brittainmark** [comment]
Got there! Re feed back from DR Byte. I think he/she (sorry don't know) is correct about the trouble shooting section of language.md in the user docs. It would be nice to include the how to see debug logs. Is there a way of creating this as a fragment and including it in both places so it does not require updating in multiple places in the future?

**Comment by brittainmark** [comment]
Another Question. Is it ok to show SQL to extract all the configuration descriptions? OR should I leave that to the developer?
In order to do a full conversion to a new language it is necessary to change the configuration table descriptions to the new language.

**Comment by scottcwilson** [comment]
- DrByte is he/him. 
- if you have content that is shared, just link to it so that it's only in one place.
- Showing SQL is very appropriate in the /dev area, but not for other areas.
- Please go ahead and add as much detail as possible, remembering that people who read (specifically) this content are not native speakers of English (and may not have dev skills) so try to make it translator-friendly.

**Comment by brittainmark** [comment]
Just tried to send accross a new set of files. got
4:29:19 PM: Build ready to start
4:29:21 PM: build-image version: ca811f47d4c1cbd1812d1eb6ecb0c977e86d1a1d
4:29:21 PM: build-image tag: v3.3.20
4:29:21 PM: buildbot version: 78b5536ab4f742c26705d3e953381b9cde6e22ef
4:29:21 PM: Fetching cached dependencies
4:29:21 PM: Starting to download cache of 558.9MB
4:29:24 PM: Finished downloading cache in 2.690888909s
4:29:24 PM: Starting to extract cache
4:29:37 PM: Finished extracting cache in 13.235409369s
4:29:37 PM: Finished fetching cache in 16.09917237s
4:29:37 PM: Starting to prepare the repo for build
4:29:37 PM: git ref pull/301/head does not exist or you do not have permission
4:29:37 PM: Failing build: Failed to prepare repo
4:29:37 PM: Failed during stage 'preparing repo': git ref pull/301/head does not exist
4:29:37 PM: Finished processing build request in 16.775987059s
what have i done wrong?

**Comment by scottcwilson** [comment]
I feel your pain. :( Likewise with my PR. 
@drbyte You're our only hope!

**Comment by drbyte** [comment]
Hmmm ... maybe github is having issues :(

**Comment by scottcwilson** [comment]
This has been fixed.  
I am going to close this ticket and open another one for the issues arising from the merge of the last PR.

**Comment by scottcwilson** [comment]
Closed via #301 and others.
