### ISSUE TITLE
Problem after installation

### ISSUE THREAD

**Issue by bristolwebdesigner** [zencart/documentation#241]
After installation I see my new menu items, they link to the pages I have created. But, if I close the browser/open and try to log back in I get a blank screen. I have to remove the files eg. new_tool_filenames.php to get back in. Then I have to upload the new_tool_filename.php again to see it in the menu. 

Clearly, the files are writen correctly otherwise it wouldn't install.

I have tried many way. I tried removing the autoloaders and the init files but this makes no difference. I realise I am missing something, can you assist me in this matter.

Regards

**Comment by scottcwilson** [comment]
Please ask this question on the Zen Cart forum.
