### ISSUE TITLE
Creating a new Admin menu item

### ISSUE THREAD

**Issue by proseLA** [zencart/documentation#255]
https://github.com/zencart/documentation/blob/master/content/dev/code/creating_menu.md

item #4 has nothing to do with creating an admin menu item.  creating a new tool, yes, but not creating a new admin menu item.

in addition, it seems like the notes is a second way to install a menu; and not really notes on installing.  i think less is more, and i'm not sure if there is a page on creating a tool (which this pages has a lot of), and this page which, IMO should be ONLY about getting a menu item onto one of the menus.

**Comment by scottcwilson** [comment]
Please go ahead and create a PR that resolves these issues.

**Comment by proseLA** [comment]
scott, considering the conversation on the zencart repo; i think it best to leave it as it.  it does document how to get it done, and considering the potential upcoming changes, i'm more than comfortable leaving it as is.
