### ISSUE TITLE
Customer & Admin Passwords both should be 16 minimum & complex including reset

### ISSUE THREAD

**Issue by chaseholden** [zencart/documentation#260]
I am surprised to see v1.5.6 still using simple 6 character passwords for customer reset passwords, which most customers will not change. 

Even Zen-cart's own documentation recommends long complex passwords, so why are your Password Resets not adhering to Zen-Cart's own recommendations? 
Plus customers are not forced to choose a new password after the reset email is used.

Please at least allow Admins to control password length + complexity requirements for customers to remain PCI Compliant.

After all, our customers save their credit card info so a hacker could easily guess their 6-character password, hack into customer's account, buy merchandise and change the shipping addresses to himself. Not cool! 

Customer passwords should be just as strict as admin passwords

**Comment by scottcwilson** [comment]
@chaseholden please open this as a request on the Zen Cart forum or an issue on the Zen Cart code repo.  It's not a documentation issue.

**Comment by drbyte** [comment]
> After all, our customers save their credit card info

Um, that's not currently a feature built-in to Zen Cart.

You can certainly customize your own store's password requirements to suit any other customizations you've made to your store.
