### ISSUE TITLE
reset admin password DOC missing pre-1.5.x SQL

### ISSUE THREAD

**Issue by mc12345678** [zencart/documentation#262]
https://docs.zen-cart.com/user/troubleshooting/reset_admin_password/

Does not address password reset for versions of Zen Cart pre-1.5.x, meanwhile there are still those upgrading from those pre-1.5.x versions that no longer appear to have access to the admin password reset option. A previous FAQ link: http://tutorials.zen-cart.com/index.php?article=2 found at: https://www.zen-cart.com/content.php?126-i-cant-login-to-the-admin-after-installing-zen-cart points to the root of the docs site... 

But then, a FAQ that I have linked (and am not providing here as I expect it too will get redirected and made unavailable without an adequate replacement) still works and DOES still have the necessary information to accomplish the desired task.

**Comment by drbyte** [comment]
>  a FAQ that I have linked (and am not providing here ... 

You mean this one?
https://www.zen-cart.com/content.php?44-how-do-i-change-or-reset-my-admin-password-(i-lost-it)

I'm not sure what part of it you mean doesn't address pre-1.5.x. You didn't mention specifics. Was it the `admin_level` field name that has you frustrated?

Instead of only posting a gripe, if you were to post what needs fixing, or better yet a PR with the actual corrections, you'd be part of the solution.

**Comment by mc12345678** [comment]
Fixed by: e567f5e373e329ee5c9c29560e115d12ee8a676e

At one point in working this I didn't have the solution because it was always available by reference... What has been done in the above commit is a solution and really at the time of writing wasn't locatable then basically the focus of the message changed...  I also was trying to move along to fix my own mistakes, etc... I am also still having difficulty with the left side menu of the docs site and have been chastised enough about referencing old help documents such as the one that contains the very old style and yet when I actually am on a computer where I can navigate the docs site to provide an up-to-date reference about how to do something I find that the original pertinent content had been omitted.
