### ISSUE TITLE
Upgrading - Detailed Instructions

### ISSUE THREAD

**Issue by dbltoe** [zencart/documentation#265]
https://github.com/zencart/documentation/blob/master/content/user/upgrading/detailed_upgrading.md

Are we not doing the folks a grave injustice by sending them into the "what did I use before" jungle rather than just load and add the current mods they might need?

Working in spite of a dead desktop or I would have submitted a change to this already.  But, I have personally seen the horror created by trying to use what was there before.  I wish there were some way to just use products/customers/orders from a db on upgrade.  The leftover/half-deleted/incorrectly upgraded files from the past are stifling.

Plus, 146 mods have been touched since the release of 1.5.6c.  Touched, in some cases, includes multiple upgrades.  The 146 is just the number of mods created since 1.5.6c.  It does not include how many times thee mod has been updated.

With the inclusion of several prior-mods, things can get dicey.  Zen non captcha was just one of the carryovers that took us off track with an upgrade from an original 1.5.0 to 1.5.6c that we upgraded to 1.5.7 for beta test.  Admittedly ZNC was small but, add five or so of those and things get squirrelly.  One of them was the reason for taking so long on the Whoops error.

Am I completely off-base with suggesting that the store owner just load a test site, add mods (Checked for currency), products, and move on?  I know that's somewhat simplistic but, I hope you get my reasoning.

**Comment by drbyte** [comment]
I've always found it easier to rebuild customizations onto a fresh install, which includes installing latest version of desired plugins. This requires a careful inspection of current site vs original ZC version release code, using that to rebuild the needed changes onto the new version. And for database, take a copy for testing/staging, but when it comes time to "go live", just directly upgrade on the live db, as this prevents data loss. Cleanup of old unneeded configurations can be done after upgrading by following whatever notes were made during staging.

I haven't read the referenced long article in a long time. This is the process I use:
https://www.zen-cart.com/entry.php?3-How-do-I-rebuild-my-site-on-the-new-version-instead-of-upgrading

**Comment by drbyte** [comment]
I've reviewed and revised large parts of the document to add some further clarity.

Also added notes that the "jungle" comparison you mentioned is intended to expose the customizations that need to be added to the new version: ie: it is indeed starting with a "new store" and copying the customizations and plugins into it. Hopefully the wording is more clear that that's what was intended all along.
