### ISSUE TITLE
Upgrading old plugins for 1.5 Compatibility

### ISSUE THREAD

**Issue by drbyte** [zencart/documentation#269]
https://github.com/zencart/documentation/blob/master/content/dev/plugins/upgrading_to_1.5.md

Scott, I'm wondering: does this page fit best here? Or should it be with the other docs related to "release-specific considerations"?

**Comment by scottcwilson** [comment]
My intention with release specific considerations was to capture gotchas.  So I'd say leave it the way it is - the upgrading to 1.5 doc is really a legacy doc.

**Comment by drbyte** [comment]
Ya, its legacy nature is what triggered the thought.
Will leave it for now.
