### ISSUE TITLE
[v158]Document changes that affect legacy plugins

### ISSUE THREAD

**Issue by zcwilt** [zencart/documentation#270]
This is not meant to address the new encapsulated plugins.
However changes like 
https://github.com/zencart/zencart/pull/3624
may break some current plugins.

**Comment by lat9** [comment]
Can you identify any plugins that provide this function and don't wrap it with a `if (!function_exists` clause?

**Comment by zcwilt** [comment]
sorry, have changed `will` to `may `

The only plugin I have downloaded that uses it is zencart-sitemap-xml and that does wrap it. 
Still think it's worth mentioning somewhere, just in case.

**Comment by scottcwilson** [comment]
I have also been intending to write a document describing the "1.5.7 Way" of building a new plugin.   More doc is needed in this area; just noticed the plugin manager itself did not have a help page.

**Comment by scottcwilson** [comment]
@zcwilt This will be done soon in /user/upgrading/release_specific_upgrade_considerations/ - preview here: https://deploy-preview-293--zencartdocs.netlify.app/user/upgrading/release_specific_upgrade_considerations/

**Comment by scottcwilson** [comment]
Can this ticket be closed?
