### ISSUE TITLE
Need to document login as customer

### ISSUE THREAD

**Issue by scottcwilson** [zencart/documentation#273]
Hoping forum user RixStix will do it, otherwise I will. 

https://www.zen-cart.com/showthread.php?226898-Login-as-customer

Start with 1.5.7 and then touch on pre-1.5.7 methods (ALAC, Master Password, EMP).

**Comment by drbyte** [comment]
Pre-1.5.7 should just mention links to plugins, not describing them in detail. Need to encourage people to move forward, not just patch the old.

**Comment by scottcwilson** [comment]
Closed by https://github.com/zencart/documentation/pull/274
