### ISSUE TITLE
Deprecate Zcgo docs in favour of Laravel

### ISSUE THREAD

**Issue by zcwilt** [zencart/documentation#281]
These docs https://docs.zen-cart.com/dev/zcgo/ are now deprecated.
With the introduction of Laravel, Zcgo is redundant in favour of Artisan.

I've already converted the make:defines (for creating array language files) to Artisan

Will up date this soon to replace with a section regarding Laravel integration

**Comment by scottcwilson** [comment]
Request for documentation: how to use Laravel to automate importing of .sql files.  (I can use this to help maintain my multiple copies of test sites on various computers.)
