### ISSUE TITLE
Manifest Files

### ISSUE THREAD

**Issue by brittainmark** [zencart/documentation#282]
https://github.com/zencart/documentation/blob/master/content/dev/plugins/encapsulated_plugins/manifests.md
"PluginId
The id number assigned by the Zen Cart forum site when submitting the plugin for review. e.g. https://www.zen-cart.com/downloads.php?do=file&id=1583 This is used to do call home checking for new versions"

The first time you submit a plugin you will not know the PluginId. Therefore is it ok to leave it blank(or assign a default no check value 0 maybe) or will you have to submit the plugin. get the id when assigned and resubmit the plugin with the id filled?

**Comment by lat9** [comment]
Hopefully, you can set that value to `0` to indicate that the plugin doesn't want to opt-into the call-home feature.

**Comment by drbyte** [comment]
1. Let's stop calling it "call home" . I'll update the original doc.
It's used to "check for new versions available in the Zen Cart plugins site".

2. Yes, if you don't yet know the ID number assigned, leave it blank or 0.
We're mulling over ideas for reserving an ID number for a new plugin so you can include it before submitting.

3. @lat9 why would you want it to not alert if a new version has been published?

**Comment by scottcwilson** [comment]
0 would be appropriate for commercial mods.
