### ISSUE TITLE
Directory Structure

### ISSUE THREAD

**Issue by brittainmark** [zencart/documentation#285]
https://github.com/zencart/documentation/blob/master/content/dev/plugins/encapsulated_plugins/directory_structure.md
When viewed in git all lines up correctly. When viewed in firefox on the zen cart site v1.0.0 and includes not correctly indented. Html 
`<li><p>rewardPoints</p></li>
<li><p>v1.0.0</p>
<ul>
<li><p>manifest.php</p></li>
<li><p>admin</p></li>
<li><p>includes</p>
<ul>
<li>auto_loaders</li>
...</ul></li></ul></li>`
Needs to be
 `<li><p>rewardPoints</p><ul>
<li><p>v1.0.0</p>
<ul>
<li><p>manifest.php</p></li>
<li><p>admin</p>
<ul>
<li><p>includes</p>
<ul>
<li>auto_loaders</li>
...
</ul>
</li>
</ul></li></ul></li></ul></li>`

Sorry don't know how the document is generated so could not fix.

**Comment by brittainmark** [comment]
This appears to be the case across all documents were the directory hierarchy is displayed. Same problem in EDGE so not firefox related.   If someone can tell me how I'm happy to go through and change.

**Comment by scottcwilson** [comment]
When I go to https://docs.zen-cart.com/dev/plugins/encapsulated_plugins/directory_structure/ in Firefox it works fine. 

<img width="1280" alt="Screen Shot 2020-07-13 at 7 00 42 AM" src="https://user-images.githubusercontent.com/4391638/87297537-96c8aa00-c4d6-11ea-827d-3bf11d7210e2.png">

**Comment by brittainmark** [comment]
Yes that's is what i see v1.0.0 should be indented to the level of manifest as the path is zc_plugins/rewardsPoints/v1.0.0 not as shown zc_plugins/v1.0.0. Also includes should be indented once more as the path is zc_plugins/rewardsPoints/v1.0.0/admin/includes not  zc_plugins/rewardsPoints/v1.0.0/includes
I think there is an issue with the document generation as if you look at the github preview it looks fine

![zc1](https://user-images.githubusercontent.com/63110817/87300125-3bfa7700-c505-11ea-9a7c-d3df16045fde.png)

 

I was also wondering as a general point if it was worth saying that you do not rename admin to (YOURADMIN) like the main admin folder.

**Comment by scottcwilson** [comment]
Thanks - I see your point now that the indentation is not exactly right.   This should be fixed now. 
Your point that the admin should not be renamed is excellent and has been added. 

Please check and if satisfied, close this ticket.
https://docs.zen-cart.com/dev/plugins/encapsulated_plugins/directory_structure/

**Comment by scottcwilson** [comment]
As documentation: Indenting in this system with bullet points requires four spaces.  If you skimp and use 2, it may appear to work in your local markdown editor/viewer but it won't work when the site is deployed live!

**Comment by brittainmark** [comment]
Great that page is fixed do you want me to edit and  create a pr for any other cases i see

**Comment by scottcwilson** [comment]
That would be fantastic, much appreciated.  Your eyes are likely sharper than mine! :)
