### ISSUE TITLE
Redirect on home page 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/documentation#3]
Guys, it seems like 
https://docs.zen-cart.com/
redirects to 
https://docs.zen-cart.com/Habitat/main

If we can instead use an index.html (perhaps maintained in this repo), we can increase the visibility of other sections of the docs; right now you have to know the URL in advance to get to them - such as https://docs.zen-cart.com/Developer_Documentation/1.6 for example.

**Comment by zcwilt** [comment]
Hi @scottcwilson 

The current documentation site is using https://github.com/codex-project 
and in fact using the old Laravel 4.2 version of code. 
This lets you set a default 'manual' that is first displayed. At the moment that is set to the Habitat documentation. 

We could set it to some other Manual, but that wouldn't help with what you are suggesting.

What could be done is to create a new 'Overview' manual that then has links to all the other manuals.

I have also been planning an upgrade to use the latest Codex version, but never find the time !

**Comment by zcwilt** [comment]
@scottcwilson

**Comment by scottcwilson** [comment]
:+1: Close when ready.  Thank you! 
If my suggestion to get the Tutorials on here is accepted, I will update the page to add it.

**Comment by zcwilt** [comment]
just testing now. We originally had a crontab that pulled in commits here directly to the documentation site. It seems yo have been broken, but hopefully working now
