### ISSUE TITLE
Order Total Modules, a discussion

### ISSUE THREAD

**Issue by lat9** [zencart/documentation#30]
I'm in the process of creating an order_total_modules.md and have come across a conundrum that is slowing me down.

Each of the order_total modules includes a function named `pre_confirmation_check` that is (to my old eyes) never called!  My read on the `pre_confirmation_check` method is that it's totally (pun kind of intended) handled by the order_total class file.

My current thought is to document the fact that many of the order_total modules include this unused method and leave it at that.  There are, additionally, some order-total simplifications that can occur!

**Comment by lat9** [comment]
Regarding the `pre_confirmation_check` method, I see that that method was in use (e.g. `ot_coupon`) for Zen Cart versions prior to zc155.

**Comment by scottcwilson** [comment]
Should this issue be closed or moved to the code repo?  It doesn't seem related to the documentation repo.

**Comment by lat9** [comment]
It could probably go 'both ways' since it affects the documentation of the order-totals' interfaces as well as the code itself.

**Comment by lat9** [comment]
What happened to all the documentation I created on the order-total and shipping modules?  Those markdown files were in the 'developer docs' but I can't find them anymore.

**Comment by scottcwilson** [comment]
Is this it?

./content/v2/code_docs/modules/shipping_modules.md
./content/v2/code_docs/modules/order_total_modules.md

It might have been accidentally classified as v2 if so.

**Comment by lat9** [comment]
Those are they!

**Comment by scottcwilson** [comment]
Whew!  OK.  A PR will get them moved to a better place if you're ready to do so.

**Comment by lat9** [comment]
Since I don't know where they are, could you do that PR?

**Comment by scottcwilson** [comment]
Happy to - how would you like them to show up in the new site?   We'd put them here:

https://docs.zen-cart.com/dev/

do you want the link to be called (say) "Code Components" ?  Or something else?

**Comment by scottcwilson** [comment]
or we could do it in the hierarchy it's in now: 
dev / code_docs / modules 

Not sure how much doc you're planning to do. :)

**Comment by lat9** [comment]
That sounds good, Scott.  I've got a (_2-year_) pending update to describe the payment modules' interfaces as well.

**Comment by scottcwilson** [comment]
Great!  Coming right up.

One thing to remember (that I always forget) - when you add a new content .md file, put the little block at the top that gives the title and sort order.  Otherwise it doesn't show up. :(

**Comment by scottcwilson** [comment]
Can this issue be closed? 

If not, what are the close conditions for this issue?  How do we know when it's done?
