### ISSUE TITLE
Directory Structure version numbering

### ISSUE THREAD

**Issue by proseLA** [zencart/documentation#338]
https://github.com/zencart/documentation/blob/master/content/dev/plugins/encapsulated_plugins/directory_structure.md

the use of the prefix `v` for a version number is confusing, and IMO, should be removed. versions should be `1.0.1`.

referencing a software version in documentation or when referring to `V 1.5.7` is 1 thing; but making the `v` part of the number seems wrong to me.

**Comment by scottcwilson** [comment]
The way it's written reflects the current reality of how the software works.     The folder `zc_plugins/DisplayLogs` has two subfolders: `v3.0.1` and `v3.0.2`.
