### ISSUE TITLE
Document listing page "Display ... " settings

### ISSUE THREAD

**Issue by scottcwilson** [zencart/documentation#429]
Each of the 4 Listing Page configuration menu items (Product Listing, New Listing, Featured Listing, All Listing) - except Index Listing - has a set of configuration values that are 4 digits each:

Display Product Image
Display Product Quantity
Display Product Buy Now Button	
Display Product Name	
Display Product Model	
Display Product Manufacturer Name	
Display Product Price	
Display Product Weight

Need a new page that explains all of this.

**Comment by wiztechinc** [comment]
This one. If you would assign it to me?

**Comment by wiztechinc** [comment]
exactly where were you intending to put the link to this new page? I'll do that one too. Got the page ready.

**Comment by drbyte** [comment]
When new files are added, the link is automatically put on the parent page

**Comment by scottcwilson** [comment]
I would also link from https://docs.zen-cart.com/user/template/listing_page_layout/

**Comment by wiztechinc** [comment]
> When new files are added, the link is automatically put on the parent page

Now that's cool!  Okay. Doesn't look like I'm gonna finish today but I'm really close.

**Comment by scottcwilson** [comment]
> Now that's cool! 

SSGs (Static Site Generators) do a lot for you so you can focus on content.

**Comment by wiztechinc** [comment]
Oh my, it did!  I see why this might be a major benefit, especially to this kind of project! Consider me tickled pink!

**Comment by scottcwilson** [comment]
Fixed by #466
