### ISSUE TITLE
Reduce duplication in Zen Cart documentation search results

### ISSUE THREAD

**Issue by scottcwilson** [zencart/documentation#458]
When you search for "Reset" in the search box, you get 4 things related to resetting the admin password: 

![image](https://user-images.githubusercontent.com/4391638/91172191-c4923880-e6a9-11ea-81dd-e2f2e6ef0bce.png)

1 a link to user/troubleshooting/reset_admin_password
2 a link to user/admin/admin_password
3 a link to user/troubleshooting
4 a link to user/admin 

Only 1 is useful.  2 is just a a redirect page. 3 and 4 are listing pages.  

I tweaked the sitemap to exclude redirect pages, and it automatically excludes listing pages. 

If you could configure Algolia to use the sitemap, the results should be more useful.
The sitemap is here:

https://docs.zen-cart.com/sitemap.xml

**Comment by scottcwilson** [comment]
Request to use Sitemap to build has been sent to Algolia today by Chris.

**Comment by drbyte** [comment]
Config updated

**Comment by scottcwilson** [comment]
The redirect page is no longer in the search results - progress!  But the two listing pages *are* still in the results, even though they are not in the sitemap.  So is the solution to tell the search to only use the title and not the description?

**Comment by scottcwilson** [comment]
I wonder if we have to ask them to remove start_urls from the config?

https://docsearch.algolia.com/docs/config-file/#start_urls

Not sure why the listing pages are still showing up because they're not in the sitemap.  Could be a question you'll have to ask them.

**Comment by proseLA** [comment]
searching the site returns no results.  at least for any of my searches.

https://docs.zen-cart.com/search/?q=reset
https://docs.zen-cart.com/search/?q=notify
https://docs.zen-cart.com/search/?q=observ

![image](https://user-images.githubusercontent.com/1095136/124160317-fe159c00-da50-11eb-9edb-801d20f9ca43.png)

**Comment by scottcwilson** [comment]
Search not working is a new issue, unrelated to this ticket.  @drbyte has been informed of the issue.

**Comment by scottcwilson** [comment]
A new ticket has been created for the recent search issues: #721.

**Comment by scottcwilson** [comment]
I think I'm ready to declare victory on this one.  New search experience is much better.
