### ISSUE TITLE
Additional listing page documentation needed 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/documentation#467]
We now have /user/template/listing_page_configuration/ which explains Admin > Configuration > New Listing, All Listing and Featured Listing pages.

We need to document Admin > Configuration > Index Listing by completing the page 
/user/template/index_listing/  

Then we need to create a new page explaining Admin > Configuration > Product Listing 

@wiztechinc please claim when ready

**Comment by wiztechinc** [comment]
me! Do I need to do more?

**Comment by scottcwilson** [comment]
No - I just need you to comment one time and then I can assign the ticket to you.  It's a quirk of how Github Issues works.

**Comment by scottcwilson** [comment]
Also there's a bug in the Index Listing page - please remove **Specials** from the list of Listing Pages (since it's really not one).

**Comment by scottcwilson** [comment]
PR #491 was great.  Please add some more: 

- When you say "Instead, the *Index Listing* settings control location, sort order, number of products per row and category filtering." I don't know what pages this applies to.  Product Listing pages?  Category pages?  What URLs?  (Remember the person reading this might have no knowledge of Zen Cart.) 

- please crosslink to the centerboxes page https://docs.zen-cart.com/user/template/centerboxes/ 

- explain **Category with Subcategories**, **Errors & Missing Products** and **Product listing**. 

- capitalize "Expected" in "(or expected)"

**Comment by scottcwilson** [comment]
You might be able to pull out some of the centerbox content - is it duplicative of what's already there?  Not sure.  Great progress - thank you.

**Comment by wiztechinc** [comment]
ew, tunnel vision!  I didn't realize the that page exists and there is already a page for the admin. https://docs.zen-cart.com/user/admin/centerboxes/

**Comment by scottcwilson** [comment]
Also explain: what is blazes is the difference between Product Listing and Index Listing? 
A list of products has a URL with the form `main_page=index&cPath=some-number` so is that an index page? a listing page? etc. 

Just image you were coming to this totally fresh.  What would you ask?

**Comment by wiztechinc** [comment]
So I ran into an issue - I am using 1.5.8 for this. I tried to make the page_not_found come up and it does not. None of the settings in configuration > Missing Page Check work - it only goes to the index page. Can you confirm that to make sure it's not just me? 

Working on it some more....

**Comment by wiztechinc** [comment]
The user/admin/centerboxes/ just doesn't seem to fit in that admin section unless that section is intended to be a collection of FAQs. Does it need renaming or rethought? It does highlight that the centerboxes are also on the empty shopping cart page and a link to the full discussion of the the stock page is warranted on both pages.  Which only presently exists in the config settings.  I added that link to both pages. 

I started editing the admin/centerboxes/ but I'm not happy because of the duplication and then being left with no discussion of the shopping cart boxes. I much prefer a full page for each config section rather than that less than detailed admin section page.  Shall I just put up that one with what I've got now so we can return to it later?

**Comment by scottcwilson** [comment]
Check Configuration > My Store > Missing Page Check is set to Page Not Found.
Then it should work: 
go to http://localhost:8888/gh_demo_158/index.php?main_page=foo
will redirect to 
http://localhost:8888/gh_demo_158/index.php?main_page=page_not_found

**Comment by scottcwilson** [comment]
Please put a document about this behavior in storefront_pages - it's incredibly confusing. I have been tripped up by it myself.

**Comment by wiztechinc** [comment]
> Check Configuration > My Store > Missing Page Check is set to Page Not Found.
> Then it should work:
> go to http://localhost:8888/gh_demo_158/index.php?main_page=foo
> will redirect to
> http://localhost:8888/gh_demo_158/index.php?main_page=page_not_found

It's not on my installation - which I just completely updated. No matter which setting I chose, I got the same response. That's why I asked. I can definitely create an issue. Was just seeing if you had heard about this not working. 

So much documentation, so little time (brain power). The good news is I actually like doing this!

**Comment by scottcwilson** [comment]
You don't need to create an issue.  There is no problem with 158.
Your fork it out of date.  When I go to https://github.com/wiztechinc/zencart it shows you're 804 commits behind. 

<img width="671" alt="Screen Shot 2020-08-31 at 6 39 39 PM" src="https://user-images.githubusercontent.com/4391638/91775576-638ec700-ebb9-11ea-8ca8-ebeacd8caccd.png">

**Comment by wiztechinc** [comment]
Uh, no, I hear what you are saying but the live site on my cpanel server is pulling from the master, not my fork. I don't have the ability to do anything more than that with the site. I just corrected the problem I had before (cause admin is renamed and not pulling the changes into that folder).

**Comment by scottcwilson** [comment]
If you can get everything else done except the stuff on the missing page, go ahead and check that in and just make a note somewhere on the page 

FIXME: add info on Missing Page 

You'll see this done elsewhere in the doc where I couldn't fully complete something.  

I'd rather see the improvements you have than wait for everything to be fully complete.
