### ISSUE TITLE
circular reference

### ISSUE THREAD

**Issue by drbyte** [zencart/documentation#507]
<img width="970" alt="Working with Additional Images  Zen Cart Documentation 2020-09-03 at 10 44 10 PM" src="https://user-images.githubusercontent.com/404472/92193779-233c7c80-ee37-11ea-9843-8cfbfe46d00c.png">

**Comment by scottcwilson** [comment]
thanks - I just reorganized some of this and was worried about doing that very thing.

**Comment by scottcwilson** [comment]
Fixed in #508.
