### ISSUE TITLE
typos - checklist

### ISSUE THREAD

**Issue by wiztechinc** [zencart/documentation#515]
https://docs.zen-cart.com/user/first_steps/basic_checklist/

As I go thru, I am finding a few typos that need fixing and was going to do several in a commit but this particular file is a concern. Some of the bolded phrases are missing the end ** for an easy fix but the question is about 10 thru 15 that don't match the previous ones. List items are prefaced with an asterisk. It looks like a simple correction to a list item but I wanted to make sure this wasn't deliberate.
I.E:
Admin - Locations/Taxes - Tax Classes * Create classes for the varying tax combinations you must assign to a product. In most cases, you only require one category.

**Comment by drbyte** [comment]
Ya, 7 and 10 are missing the closing double-asterisk for the bold stuff.

And 10-15 need another space before the bullet asterisks

**Comment by scottcwilson** [comment]
> As I go thru, I am finding a few typos that need fixing and was going to do several in a commit ...

It's probably better for you to do them one file at a time - it's less likely someone will have updated the file underneath you, creating a merge conflict.

**Comment by scottcwilson** [comment]
Thanks for your updates!
