### ISSUE TITLE
How do I Install 

### ISSUE THREAD

**Issue by wiztechinc** [zencart/documentation#522]
https://docs.zen-cart.com/user/first_steps/how_do_i_install/

The B step is a quite clear description of how to get the zipped files on the server. But the instructions leave the site owner with a folder which instructions have already stated elsewhere that is not the best location. I think we need to also talk about moving the files to the root.  Instead it just skips to set permissions on folders.

**Comment by wiztechinc** [comment]
There is a typo on this page that I have ready.

**Comment by scottcwilson** [comment]
I'm not sure why you say, 
> instructions have already stated elsewhere that is not the best location.

It's one of several installation options.  See 
https://docs.zen-cart.com/user/first_steps/deployment_configurations/ 

If you want to clarify that the files can in be in root as well in step B, go for it.

**Comment by wiztechinc** [comment]
My problem is that the section is really detailed - but then leaves out any mention of maybe moving the files to the root. If I were new to this, I would be going what now and didn't they say not to do this? Where did I read that? Am I remembering this wrong? Gee, should I leave the store in that place? I recently worked on a site that was in a folder but the owner never realized the root of his domain had nothing and there was no redirect to his store. 

And believe me I do look at some of this with my first experience in mind - oscommerce instructions said to create a database string - it took me weeks to figure that out. So sometimes being extremely detailed and literal is more appropriate than others. 

Now, maybe just line with link to the discussion? I dunno - and right now don't remember where that discussion was or exactly how it was phrased. I just feel like the subfolder situation may need to be addressed here in more detail.

**Comment by scottcwilson** [comment]
Rather than "moving files to the root" I'd say describe the root as another possible installation location.   Point to the deployment_configuration help file and reference configuration option 1, 4, etc.

**Comment by drbyte** [comment]
The point is valid, but I agree: fix up everything else, and then we can tackle the idea of moving to root as a separate exercise.

**Comment by wiztechinc** [comment]
Got it.
