### ISSUE TITLE
Huh? 

### ISSUE THREAD

**Issue by wiztechinc** [zencart/documentation#526]
https://docs.zen-cart.com/user/new_user_topics/sales_message/

The last part prefaced by NB? 
NB: By default, the text “Sales Message Goes Here” is also located in includes/languages/english/header.php

Should I pay attention to this or is this messaging for someone not to forget the line who may be circling back to it?

**Comment by drbyte** [comment]
Ya, something's wrong there.

The constant name is correct. But `classic` has an override with the 2nd phrase in it. So the filename path in the 2nd case is wrong.

**Comment by wiztechinc** [comment]
Oh, I see. So maybe pics of both responsive & classic might help here? Or should someone look at making these the same since it's actually a minor change? I actually prefer sales message over tagline and that will hang on for a long time to come... Talked myself into pics only! :) What say you?

**Comment by drbyte** [comment]
I don't think there's any need to add pics.

The only reason for the `classic/header.php` lang file is for this exact override text.

So, unless overrides still aren't clear after all the other documentation about it, I don't think there's anything to fix here other than the path ... or just delete the "NB" part altogether.

**Comment by wiztechinc** [comment]
My preference is to delete.

**Comment by drbyte** [comment]
Closed by #528
