### ISSUE TITLE
improvement

### ISSUE THREAD

**Issue by drbyte** [zencart/documentation#537]
Point 1:
Pages are listed with a Title and a Description, and the Description only appears when the Title is used as a Link to the "actual" page.  (Point: Description has no in-page purpose.)

Point 2: 
The Description doesn't seem to have much other purpose either, particularly where there's no actual need to describe the Title.

Case in point: 
I'm finding more and more subtitles (aka "description" I guess) that are just "Zen Cart `______`" where `_____` is just the `title` repeated.
This image is one of a hundred that are essentially the same:
<img width="436" alt="Catalog  Zen Cart Documentation 2020-09-08 at 8 19 51 PM" src="https://user-images.githubusercontent.com/404472/92540278-0d053680-f212-11ea-9585-35a1b307aeea.png">

I realize the intention of adding "Zen Cart" in front of everything was to not do a direct repeat of the title,
and while it's flattering to smatter the brand name in every possible nook and cranny,
if I were the end-user I'd be experiencing eye-fatigue at seeing the words "Zen Cart" every other sentence.

## Thought:
If the title is descriptive enough, then there won't need to be a subtitle/description.
Therefore there won't be any worry about repetition/duplication of title into description since we can delete the description.

Or is there some important added benefit that it's required for?

**Comment by scottcwilson** [comment]
See #344. I am working on fixing these.

**Comment by drbyte** [comment]
I didn't want to clutter that other Issue.

I still think sections like this one have no need to list a description. These are names of pages in the menu, where the titles match the menu names.

Is the description used for anything else? If it's only used for subtext, then ... well, now I'm repeating myself.

**Comment by scottcwilson** [comment]
It's used in building meta tags, and it can be used in search depending on how things are configured. 

When you say, "Sections like this one," you mean this, right: 
https://docs.zen-cart.com/user/admin_pages/catalog/ 

If so, yes, the admin pages are a tough call - it might be worth getting rid of the descriptions there.
