### ISSUE TITLE
Idea: Rename "Performance" category to "Speed"?

### ISSUE THREAD

**Issue by drbyte** [zencart/documentation#575]
While the geek in me will see the category "Performance" and think of "website speed", database optimization, loading times, etc, .... I imagine the non-techie storeowner will think of "how are my products performing", ie: sales reporting etc.

So I'm thinking that our 5 current pages in "Performance" could be recategorized as "Speed",

Then, secondarily, explore (I say explore because I haven't looked into it yet to know) whether others that relate to "sales reporting" and product-performance (and maybe built-in analytics things like "visit counter") are all grouped together appropriately. (I don't see a "Reports" category at the top level ... only several layers deep to be found if you know to navigate into the specific admin menus called Reports)

Thoughts?

**Comment by scottcwilson** [comment]
I am open to both.  I am actually working on the customer referral pages now.  
Should we say "Website Speed?"  "Store Speed"?  Or maybe just speed.  Not sure.  Noodle on it. 

Do you like "Reports" over "Analytics"?  (I think I do - just checking.) 
I will get these referral changes checked in today.

**Comment by scottcwilson** [comment]
Added Reporting.   There are only a few files in it - if you think others are good candidates please add (and use the `alias` trick described in the CONTRIBUTING.md file so any links won't break).

**Comment by drbyte** [comment]
> Should we say "Website Speed?" "Store Speed"? Or maybe just speed. Not sure. Noodle on it.

Speed is fine.  If I'm looking at a list of categories I won't find "Speed" under "W" ("W"ebsite) very quickly ;)

> Do you like "Reports" over "Analytics"? (I think I do - just checking.)

Later it may make sense to have both. For now Reporting is fine.

**Comment by drbyte** [comment]
Thinking more about the Analytics one.

Debating the right category name. Things that come to mind are:
- Analytics
- Metrics
- Performance
Trying to think in terms of the storeowner: what would they search for? (and use that to inform the decision of the category or its subtitle)

I envision the content in this category being related to:
- accessing traffic stats (eg: admin dashboard)
- analytics (things like integrating tools, maybe listing the ec_analytics plugin)
- maybe list the User Tracking plugin ... undecided about that. Don't really want a page just for that topic.
- link to admin dashboard widgets info (list, creating, etc)

**Comment by scottcwilson** [comment]
You decided against Reporting?  I thought it was the most obvious.

**Comment by drbyte** [comment]
No, I see analytics as different from reports

**Comment by scottcwilson** [comment]
Oh ok I see.  Analytics is good - lots of people are familiar with this term.

**Comment by drbyte** [comment]
I'm good with that.

**Comment by scottcwilson** [comment]
Analytics done too. 
These categories are a bit skimpy now but they will grow in time.

**Comment by drbyte** [comment]
Thx
