### ISSUE TITLE
Collapse duplicate pages related to updating old code

### ISSUE THREAD

**Issue by drbyte** [zencart/documentation#593]
Most of what's in `/user/troubleshooting/php_debug_logs.md`
is already in the more detailed `/user/upgrading/php_warnings.md`

(I just added a bunch of content to the latter, and then discovered the former had mostly duplicate content.)

Perhaps the former can be converted to a link to the latter? (I suspect a bunch of internal crosslinks may also require updating if we do that.)

Thoughts?

**Comment by scottcwilson** [comment]
OK

**Comment by scottcwilson** [comment]
I removed the duplicate content but kept the first page as a "why" - the second page is "how to fix."  Take a look and see if you agree.
