### ISSUE TITLE
Feature request: Additional reference to database user permissions/setup

### ISSUE THREAD

**Issue by mc12345678** [zencart/documentation#625]
Maybe this needs to be just a personal issue rather than posted here. 

Issue: Went to try to find the minimum database permissions necessary to setup a new "temporary" store. Didn't find the information in the User side for databases, 

So didn't find it at: https://docs.zen-cart.com/user/first_steps/database/
Not here: https://docs.zen-cart.com/user/first_steps/components/
Not here: https://docs.zen-cart.com/user/first_steps/deployment_configurations/
Not here: https://docs.zen-cart.com/user/first_steps/hosting/
Not here: https://docs.zen-cart.com/user/first_steps/basic_checklist/

Finally found it on this page: https://docs.zen-cart.com/user/first_steps/how_do_i_install/
at this specific location: https://docs.zen-cart.com/user/first_steps/how_do_i_install/#5-have-you-created-a-database

While some of the above locations may not apply nor be "appropriate", it seems like there could be some sort of bread crumb to that information.

Unfortunately at the moment I'm working on something else, but as I said, wanted to document this somewhere... Maybe there's more/better information in the developer side, but considering the issue related to store installation/setup, it made sense to me that it would be on the catalog/user side and I didn't want to just shotgun the all permissions action to instead keep the database as secure as possible/necessary by only allowing the necessary permissions.

Or maybe I just need to change my perspective in what might be expected of the docs or how to find things in them. Maybe I need to do with them like I did in the old FAQ area which was basically read through each one so that I can become familiar with where to find the information I might need...

**Comment by drbyte** [comment]
Cross-linked via https://github.com/zencart/documentation/commit/e5ef0bab8d7f50547ae09952aef7a3cde4676a0a
