### ISSUE TITLE
Creation of database: collation?

### ISSUE THREAD

**Issue by torvista** [zencart/documentation#658]
> Open your hosting account's control panel.
> Find the "Databases" section
> Choose the MySQL option
> Click on the option to Create a database.  Enter a name for it and submit. (Record the name for use in Zen Cart)

Why no mention of collation or character sets?

In the ZC fileset docs for installation, it goes in great detail through the installer steps until the point where it mentions that the database should have been previously created....I think that should be mentioned before the installer as that immediately stops the process and sends the user off in another direction. But it is not mentioned at all and again omits anything about collation/characters sets.

**Comment by scottcwilson** [comment]
Please submit a PR.

**Comment by torvista** [comment]
I don't mind writing it...but to say what exactly?

**Comment by scottcwilson** [comment]
I thought you were wanting to add content on collation and character sets? 

But the placement you suggested seems wrong - when you are in cPanel creating a database, you just pick a name, you don't set the collation or character set.

**Comment by torvista** [comment]
Sure, but should you not subsequently set what you want to use in phpmyadmin before installing?

**Comment by scottcwilson** [comment]
Why ? If you use the defaults, it does what is desired.

**Comment by drbyte** [comment]
I made this update yesterday in response to this discussion: https://github.com/zencart/documentation/commit/00dd3df7ebc16f2ec2c7c64fa82fb087d9a2d769
However, I too am not convinced this is the best place for it, particularly because this area reads more like how to create a database in cPanel, which as Scott mentions is an extremely generic action.
