### ISSUE TITLE
Link on Debug Logs Page

### ISSUE THREAD

**Issue by dbltoe** [zencart/documentation#705]
On https://docs.zen-cart.com/user/troubleshooting/debug_logs/, after a lengthy discussion, the heading How to Fix Common Debug FIles is presented with a link to "PHP Warnings and Deprecated messages after upgrading".  The current link is going to the same page, https://docs.zen-cart.com/user/troubleshooting/debug_logs/.

Should it not be pointing to https://docs.zen-cart.com/user/upgrading/php_warnings/

**Comment by scottcwilson** [comment]
Thank you - will fix on next checkin.
