### ISSUE TITLE
Configuration > Logging Options

### ISSUE THREAD

**Issue by dbltoe** [zencart/documentation#706]
Report All Errors for both the admin and store suggest the use of IgnoreDups.
I see no such option in 1.5.7c and a search of IgnoreDups in the documentation returns not found.
Was this possibly done in anticipation of lat9's report all errors being added?

**Comment by drbyte** [comment]
Admin->Configuration->Logging ...

New installs:
<img width="406" alt="Screen Shot 2021-05-22 at 2 31 49 PM" src="https://user-images.githubusercontent.com/404472/119237383-82980500-bb0a-11eb-9580-5159ea4e4d91.png">

Or upgraded from older versions might contain some older logging entries:
<img width="588" alt="Screen Shot 2021-05-22 at 2 32 47 PM" src="https://user-images.githubusercontent.com/404472/119237421-b541fd80-bb0a-11eb-880a-9fe7efa135ba.png">

And clicking the Edit button on one of those Report Errors settings allows choosing IgnoreDups:
![Admin Configuration Logging 2021-05-22 at 2 34 52 PM](https://user-images.githubusercontent.com/404472/119237474-fe924d00-bb0a-11eb-9bf4-5c9c6ca8614d.jpg)

Is this not what you're seeing?

**Comment by scottcwilson** [comment]
@dbltoe Can this be closed?
