### ISSUE TITLE
Search in Documentation Site is broken 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/documentation#721]
Recently the top search bar on https://docs.zen-cart.com/user/ stopped working.  Perhaps this is because of adjustments made by Algolia?

**Comment by drbyte** [comment]
Algolia attempted a fix last week: https://github.com/algolia/docsearch-configs/pull/4269
I'm not certain that their changes were correct.

Their crawler is allegedly reporting `503` responses.

**Comment by proseLA** [comment]
is algolia a paid service?  have you though about using the search powered by google (the evil empire)?

**Comment by drbyte** [comment]
Algolia is free for Open Source projects.
Algolia is the best de-facto standard for search. The in-page search widget is fast and easy and efficient. Plus they're typically less maintenance hassle than google search.

The present issue could be a problem in Netlify's hosting, but I haven't seen any settings to control it.

**Comment by scottcwilson** [comment]
Seems to be fixed, closing this issue.  Thanks @drbyte!
