### ISSUE TITLE
search in local spinup...

### ISSUE THREAD

**Issue by proseLA** [zencart/documentation#724]
there currently is a problem with the ssl cert for the docs site.  the ssl cert is now coming from cloudfare and i personally can not get to the site.

so i decided to spinup my local copy as indicated by the docs:
```
hugo server
```
which works all fine and dandy.  except if i try to search my local spinup, the algolia search results (now working) are linking me back to the docs site as opposed to my localhost.  which is currently not working for me as mentioned above.

is there a way to configure this algolia for the host?  i have not really dug into it.

**Comment by drbyte** [comment]
> there currently is a problem with the ssl cert for the docs site. the ssl cert is now coming from cloudfare and i personally can not get to the site.

I was tinkering with some DNS settings which broke that temporarily. Should be fine now, except that your browser might have cached the incomplete DNS change, so may have to wait for that TTL to reset. Using another browser is a good temporary workaround.

**Comment by scottcwilson** [comment]
I think this can be closed; please re-open if I am mistaken.

**Comment by proseLA** [comment]
i am not sure if this should be re-opened or not.

as long as https://docs.zen-cart.com/ is up, i have no need to spin up the docs server on my local machine.

however, if i do spin it up, and then do a search, the algolia search results links reference the https://docs.zen-cart.com/ site, not my http://localhost:1313/ server.

personally, i do not think this is ideal.  but i understand that people are busy, and that this situation is certainly very low on the totem pole.
