### ISSUE TITLE
Search box not displayed

### ISSUE THREAD

**Issue by mc12345678** [zencart/documentation#779]
Having finally updated to a new(er) mobile device, Samsung with Android 12.0, when visiting the docs site the search box is not displayed. Modes attempted using Chrome version 97.0.4692.98 are:
Standard mobile in portrait. 
Standard mobile in landscape. 
Full browser in portrait. 
Full browser in landscape.

**Comment by scottcwilson** [comment]
Yep same with iPhone.

**Comment by scottcwilson** [comment]
This issue is up for grabs for anyone who'd like to learn more about Hugo 

https://gohugo.io/

and the Google Docsy template

https://github.com/google/docsy

**Comment by simon1066** [comment]
I'll take this on, it'll give me a chance to try out my shiny new Hugo server which I've managed to at last get working.
