### ISSUE TITLE
admin custom cron job

### ISSUE THREAD

**Issue by daphilli224** [zencart/documentation#801]
I have followed the directions given in the documentation but am getting the following error message when executing my custom cron job:
[04-Mar-2022 15:30:00 America/New_York] Request URI: cron, IP address: cron
#1  mysqli_connect() called at [/path to site/includes/classes/db/mysql/query_factory.php:63]
#2  queryFactory->connect() called at [/path to site/renamed_admin/includes/init_includes/init_database.php:18]
#3  require(/path to site/renamed_admin/includes/init_includes/init_database.php) called at [/path to site/renamed_admin/includes/application_bootstrap.php:162]
#4  require_once(/path to site/renamed_admin/includes/application_bootstrap.php) called at [/path to site/renamed_admin/includes/application_top.php:15]
#5  require(/path to site/renamed_admin/includes/application_top.php) called at [/path to site/renamed_admin/my_custom_cron.php:55]
--> PHP Warning: mysqli_connect(): (HY000/2002): No such file or directory in /path to site/includes/classes/db/mysql/query_factory.php on line 63.

I assume it can't find the file where function mysqli_connect is and I'm not sure where it is. A search of my site failed to find it and I don't know where it is. I have uncommented the define for DB_SOCKET but no difference. The cron file is in the admin directory and the cron job is executing but failing at line 55 where the code is require(includes/application_top.php). If this is not the right place to post this issue, I apologize. Please let me know where I should post this issue.

**Comment by scottcwilson** [comment]
Please post a link to the documentation you are reading.

**Comment by scottcwilson** [comment]
And actually, please go ahead and post this to the forum.  Others will benefit from reading the resolution.
