### ISSUE TITLE
Document new Square module 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/documentation#813]
need installation and upgrading instructions.

**Comment by dbltoe** [comment]
[SquareWebPay_Instructions.pdf](https://github.com/zencart/documentation/files/8474293/SquareWebPay_Instructions.pdf)
This is what I sent out to our customers.  It does not cover new ZC installation and creating a new Web Application on Square.  It is for those who are moving from Square to Square WebPay.

HTH

**Comment by dbltoe** [comment]
I'll just mention that I'm just now starting taxes.
Won't be able to do much more than Red Bull for a few days.

**Comment by scottcwilson** [comment]
Paul had suggested that perhaps @brittainmark could help out here too.

**Comment by scottcwilson** [comment]
We have @dbltoe's writeup on installing Square Web Payments here: 

https://myzencarthost.com/index.php?rp=/knowledgebase/4/How-to-Activate-the-Square-WebPay-Module.html

I have a couple of clients I will be converting from Square Payments Form and I'll be adding notes to the Zen Cart documentation as I do it.

**Comment by scottcwilson** [comment]
https://docs.zen-cart.com/user/payment/square/ has been updated.
