### ISSUE TITLE
Invalid Download Links

### ISSUE THREAD

**Issue by dbltoe** [zencart/documentation#821]
None of the 1.5.x series links on https://docs.zen-cart.com/history/v15x/ are valid links.  This is the link to older versions provided at https://www.zen-cart.com/index.php when clicking on "Click here to download older versions".  This appears to be the only way to get to the

If you copy the link to see where it's going, you get https://https//docs.zen-cart.com/release-zips/15x-series/zen-cart-v1.5.7c-03052021.zipdocs.zen-cart.com/history/v15x/.

I have not been able to determine the correct link.  I am assuming it should be something like https://zipdocs.zen-cart.com/history/v15x/zen-cart-v1.5.7c-03052021 but that does not work either.

**Comment by scottcwilson** [comment]
thanks for reporting - we're trying to get away from SourceForge but for now you can always go back there if you need something older.

**Comment by scottcwilson** [comment]
This has been fixed.
