### ISSUE TITLE
Square Affiliate Link

### ISSUE THREAD

**Issue by simon1066** [zencart/documentation#835]
In [https://docs.zen-cart.com/user/payment/square/](url), perhaps the link to Square in the sentence

'You may create a Square merchant account at [squareup.com](https://squareup.com/).'

could be the Zen Cart affiliate link as on [https://www.zen-cart.com/content.php?349-Square-Payments-for-Zen-Cart](url)

assuming it is still current - [https://squareup.com/t/f_partnerships/d_partnerpage/p_zencart/c_general/o_free_processing/u_signup/l_us?route=signup%3Fsignup_token%3D6BB5B2E676](url)

**Comment by scottcwilson** [comment]
@zcwilt @drbyte please confirm and I will make this change.
Thanks for catching that @brittainmark !

**Comment by zcwilt** [comment]
@scottcwilson sounds good

**Comment by scottcwilson** [comment]
OK it will be part of my next doc checkin.
