### ISSUE TITLE
Obsolete statement in Contributing.md

### ISSUE THREAD

**Issue by simon1066** [zencart/documentation#846]
In the CSS section of Contributing.md - https://github.com/zencart/documentation/blob/master/CONTRIBUTING.md#css - I don't believe the following is any longer necessary:

> When you change these files, you must restart hugo server; they are not rebuilt the way content files are.

On my local copy (Hugo v.0.100.1) the restart is automatic with any changes to `_variables_project.scss` and `_styles_project.scss` causing an automatic rebuild of the server and a page refresh.

The only thing different on my setup is that I don't have Git installed.

Edit: I should perhaps expand on my last sentence in case it has a bearing. As I use SourceTree instead of Command Line I didn't want to install Git aswell so I set `enableGitInfo = false` in config.toml to enable Hugo to run.

**Comment by scottcwilson** [comment]
I don't know the circumstances in which this is true or false, I just remember it being incredibly confusing when I was first working on this stuff.   You may be using a more recent version of Hugo.

**Comment by simon1066** [comment]
Now that I've used Hugo a bit more the `hugo server` command seems to default to Fast Render mode

`Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender`

Not sure I fully grasp it all as I thought I was getting a full rebuild (when I apparently wasn't) so probably best to leave the Contributing.md as is. I'll close this.

**Comment by scottcwilson** [comment]
Maybe "must" should be "might need to" - just not sure.  That's really deep in this stuff, I haven't done changes in that area for a long time.
