### ISSUE TITLE
Possible changes to Section Menu

### ISSUE THREAD

**Issue by simon1066** [zencart/documentation#847]
I do find the left menu sidebar to be a bit difficult to navigate. The sidebar defaults with all sections expanded, showing all pages - that's a lot to scroll through. It's only after clicking on a section heading that everything but that section collapses, that's a bit more manageable but can still be a lot of pages to scroll through to get to the next section (First Steps for example).

I note that the Docsy submodule Zen Cart Docs uses hasn't been updated in 3/4 years, since then there has been a foldable section menu introduced, as exampled on this page:  https://deploy-preview-518--docsydocs.netlify.app/docs/adding-content/navigation/#section-menu

**Comment by scottcwilson** [comment]
Give it a shot, let's see how it looks.

**Comment by simon1066** [comment]
I'm think this might be above my pay grade. I believe the Docsy fileset used for the Docs is based on a 2019 sub-module commit by @drbyte (image attached) and in order to implement the collapsible side bar sections the theme commit would need to be updated (beyond my skillset). Whether a theme update would lead to unexpected behaviour of the Docs, I don't know.

![Screenshot 2022-06-06 085350](https://user-images.githubusercontent.com/13421449/172119557-b164d234-9e66-40d9-9382-8e191d60a73a.png)

**Comment by simon1066** [comment]
Yes, I think I can build a PR - it won't be small. I'm all hugo/docsy'd out for a bit but will get on to it.

If we are to leave a search box in the sidebar then I'll also amend the code to not have a search box in the header on mobile devices, as was the case with my previous PR.

**Comment by scottcwilson** [comment]
I had forgotten that you fixed the missing search on mobile!  Thanks for doing that. 
Well, this is not a rush, take your time.  But I do think it looks fantastic - definitely an improvement.

**Comment by scottcwilson** [comment]
Just updated the Docsy template to fix the google_news internal template issue.

**Comment by simon1066** [comment]
I'll resubmit this PR to take account of this Docsy template upgrade.
