### ISSUE TITLE
https://docs.zen-cart.com/dev/contributing/coding_standards/

### ISSUE THREAD

**Issue by torvista** [zencart/documentation#88]
>Where possible, (new) code should always output HTML/CSS/JS directly, and NOT use PHP to echo the HTML.

I think the only notable exception is /form to close zen_draw_form? So should be mentioned?

**Comment by scottcwilson** [comment]
The more clear, the better.  Go for it.

**Comment by torvista** [comment]
Any other exceptions?

**Comment by scottcwilson** [comment]
Thinking some more, I am not sure I would even call this an exception.  This is done in some places as a convenience, but it could just as easily be done in raw HTML.  It's certainly not required.

**Comment by torvista** [comment]
It gets picked up by phpstorm as an error/unbalanced tag if it's closed as html but opened by php/the function. I assume other IDEs would do the same since they cannot match an opening tag

**Comment by scottcwilson** [comment]
Oh! OK this is a change in 1.5.6 that I had completely forgotten about.  OK maybe make the exception less specific then - something like, "the rule is not required in cases where a block is opened by PHP (as in zen_draw_form), since this will confuse IDEs."

**Comment by scottcwilson** [comment]
I have added change this to my next documentation PR.
