### ISSUE TITLE
Search result links to code_docs

### ISSUE THREAD

**Issue by simon1066** [zencart/documentation#887]
Not too sure what's causing this but if, at https://docs.zen-cart.com, I search for `template`, the real-time search results look like this:

![image](https://user-images.githubusercontent.com/13421449/185467610-47de9743-ad72-41f0-81aa-4e7a5195a4e8.png)

Clicking on the first 'Templates' link takes me to https://docs.zen-cart.com/v2/code_docs/querybuilderdefinitions/templates/#templates which is obviously not right.

**Comment by simon1066** [comment]
Ah yes, I see now. The v2 content is included in search results, perhaps there's a way to exclude it.

**Comment by scottcwilson** [comment]
@zcwilt  can we tweak the algolia config to omit some paths from search results?

**Comment by scottcwilson** [comment]
Closing as a dup of #1106
