### ISSUE TITLE
Color Contrast fix for footer links

### ISSUE THREAD

**Issue by dbltoe** [zencart/documentation#888]
Can't find the file listed as https://docs.zen-cart.com/scss/main.min.b67a32d62d551cfc342571968c45e49d5f5b5cddcb7d098ae1ccf1c2c42b419a.css

The following needs to be added to correct the color contrast in all the footer links.

`.col-12.col-sm-4.text-center.py-2.order-sm-2 a {color: #6aafff;}
.col-12.col-sm-4.text-center.py-2.order-sm-2 a:hover {color: #f2f2f2;}`

**Comment by simon1066** [comment]
That file is part of the Docsy template and is non-editable. There are CSS override files that you can add that code to,

https://github.com/zencart/documentation/blob/master/CONTRIBUTING.md#css

**Comment by dbltoe** [comment]
THANX
Fixed with PR #889
