### ISSUE TITLE
How Many Legacy Links are Needed on the Main Page?

### ISSUE THREAD

**Issue by dbltoe** [zencart/documentation#890]
This is a screenshot of the code inside the main role and footer section on the main page.

![image](https://user-images.githubusercontent.com/5122886/185684892-95b90e59-6e19-42d5-9fb8-8fa9d9c104d5.png)

**Comment by scottcwilson** [comment]
What URL are you using ?  I don't see this on view-source:https://docs.zen-cart.com/

**Comment by dbltoe** [comment]
It's an inspect vs view source

**Comment by scottcwilson** [comment]
Not sure.  But they don't show up anywhere but inspect.

**Comment by dbltoe** [comment]
If you do an ANDI or Axe DevvTools check of the main page, they both show the link 15 times.

**Comment by zcwilt** [comment]
Found the issue here 

```<li><a href="https://www.zen-cart.com/content.php?2-FAQs-and-Tutorials">Legacy FAQs</li>```

Noe: there is no closing `</a>` tag in the `<li>` block
