### ISSUE TITLE
Template needs to be updated

### ISSUE THREAD

**Issue by scottcwilson** [zencart/documentation#905]
See https://github.com/gohugoio/hugo/issues/9172

```
WARN 2022/09/03 14:53:23 The google_news internal template will be removed in a future release. Please remove calls to this template. See https://github.com/gohugoio/hugo/issues/9172 for additional information.
WARN 2022/09/03 14:53:23 .Path when the page is backed by a file is deprecated and will be removed in a future release. We plan to use Path for a canonical source path and you probably want to check the source is a file. To get the current behaviour, you can use a construct similar to the one below:

  {{ $path := "" }}
  {{ with .File }}
	{{ $path = .Path }}
  {{ else }}
	{{ $path = .Path }}
  {{ end }}
```

**Comment by scottcwilson** [comment]
Can't seem to get Hugo to show the offending file even with `--panicOnWarning`.  I'm guessing it's one of: 

```
layouts/partials/footer-edit.html
layouts/partials/page-meta-links.html
```

**Comment by simon1066** [comment]
While the Docsy template that ZC uses has been updated to remove the call to the `google_news` template (https://github.com/zencart/documentation/commit/2ab483d1b281c544a7ddfdff746ec8e28c9f3af7) doesn't the gohugio link above indicate that the deprecation warning is due to the `google_news` internal template being present in Hugo, when it shouldn't be. We should probably be upgrading the version of Hugo we use - that internal template was removed (and the warning added) from Hugo in 2021 (https://github.com/jmooring/hugo-docs/commit/1ba3de3c1e9e8c275b1b23a59667cd1875400a83). It also needs to be upgraded if we want to implement collapsible siderbar menus.

**Comment by scottcwilson** [comment]
I'm running hugo v0.103.0+extended darwin/amd64 BuildDate=unknown (latest as of right now) and I still get the error.

**Comment by scottcwilson** [comment]
Just upgraded the Netlify build version of Hugo to the same (v0.103.0).

**Comment by simon1066** [comment]
I no longer get the `google_news` warning so looks like that's fixed. Re the .Path warning, with`--panicOnWarning` I have 

`Error: Error building site: failed to render pages: render of "page" failed: "D:\Hugo\Sites\zc_documentation\layouts\dev\single.html:2:3": execute of template failed: template: dev/single.html:2:3: executing "main" at <.Render>: error calling Render: "D:\Hugo\Sites\zc_documentation\content\dev\admin\templating.md:1:1": failed to execute template dev/content.html: "D:\Hugo\Sites\zc_documentation\layouts\dev\content.html:6:6": execute of template failed: template: dev/content.html:6:6: executing "dev/content.html" at <partial "morehelp.html" .>: error calling partial: "D:\Hugo\Sites\zc_documentation\layouts\partials\morehelp.html:11:7": execute of template failed: template: partials/morehelp.html:11:7: executing "partials/morehelp.html" at <partial "footer-edit.html" .>: error calling partial: "D:\Hugo\Sites\zc_documentation\layouts\partials\footer-edit.html:4:65": execute of template failed: template: partials/footer-edit.html:4:65: executing "partials/footer-edit.html" at <.Path>: error calling Path: Warning trapped. Remove the --panicOnWarning flag to continue.`

Seems to me that `partials/footer-edit.html:4:65` is the crucial bit and that the .Path references in that file need to be wrapped using `with .File`. Beyond me I'm afraid but has been discussed in this post - https://discourse.gohugo.io/t/path-when-the-page-is-backed-by-a-file-is-deprecated/36842/4

**Comment by scottcwilson** [comment]
Thanks for doing this test - I can probably track it down from here.

**Comment by scottcwilson** [comment]
Should be fixed now.
