### ISSUE TITLE
Sidebar menus are collapsed 

### ISSUE THREAD

**Issue by simon1066** [zencart/documentation#914]
Following the recent Docsy template upgrade, the sidebar menu is now collapsed on these pages:

https://docs.zen-cart.com/user/
https://docs.zen-cart.com/dev/

this is due to the ZC override of  `layouts/partials/sidebar-tree.html`

This will be fixed as part of the 'Adding foldable functionality to sidebar menu sections' I am currently working on.

**Comment by scottcwilson** [comment]
Things look better now.  Thanks again @simon1066 !
