### ISSUE TITLE
Inabiltiy to Use target-"_blank"

### ISSUE THREAD

**Issue by dbltoe** [zencart/documentation#975]
It would be nice to have the ability to make a lot of the Docs links open in a new window.

Is the function at https://github.com/11ty/eleventy/issues/2301 a possibility?

**Comment by scottcwilson** [comment]
You can use raw html in markdown (and add things like target="_blank").
If you just want it for your own use, right click and say "Open in new Window."

**Comment by dbltoe** [comment]
I was trying to do a PR for Timezone settings where it goes to the list of time zones and could not figure out how to set it in the link.
If you can do that one, I can see the format I should use if I think other links might work better by opening a new window.

**Comment by scottcwilson** [comment]
I'd really rather not pursue this.  If people really want a new window they can use the built-in browser abilities.
